### ISSUE TITLE
Task complains about dodger-blue-text: "Give your h1 element with the text I am dodger blue! the color dodger blue."

### ISSUE THREAD

**Issue by evaK-de** [FreeCodeCamp/FreeCodeCamp#10523]
Challenge [use-hex-code-to-mix-colors](https://www.freecodecamp.com/en/challenges/html5-and-css/use-hex-code-to-mix-colors) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html
    
    
<style>
.red-text {
  color: #ff0000;
}
.green-text {
  color: #00ff00;
}
.dodger-blue-text {
  color: #1e90ff;
}
.orange-text {
  color: #ffa500;
}
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="green-text">I am green!</h1>

<h1 class="dodger-blue-text">I am dodger blue!</h1>

<h1 class="orange-text">I am orange!</h1>

    ```
    
Screenshot:
![image](https://cloud.githubusercontent.com/assets/3306170/18378269/47f34348-766c-11e6-8fb7-6e2da365ced7.png)

**Comment by sergey-zhuravel** [comment]
Confirm in Google Chrome. The bug was introduced with FCC update. The required color for dodger blue text was updated in the challenge.

**Comment by erictleung** [comment]
@evaK-de thanks for the issue. Yes, this is an issue. The challenge was updated recently but I guess that the one test wasn't updated.

[This line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/d892172be71c62e61298b2299b3935faa7341892/seed/challenges/01-front-end-development-certification/html5-and-css.json#L4830) needs to be updated so that it matches the pattern for the `rgb` code for the color, rather than the hex code.

**Comment by mugiwarahiei** [comment]
Any fix for this one?

**Comment by apurv-thakur** [comment]
Any way to overcome this issue or should I wait for update?

**Comment by midnightdk** [comment]
same too, chrome and opera give same error and firefox show error on every h1 code

**Comment by mpgraci** [comment]
Having the same issue.

**Comment by ashishdommety** [comment]
Great to be a part of the community! Facing the same issue

**Comment by JoaoHenriquedeSouza** [comment]
I'm having the same issue the table dysplays the hex code for dodger blue color as #1E90FF but when i try to run i get an error.

**Comment by jbradshaw4** [comment]
How do we move forward?

**Comment by ashishdommety** [comment]
Just go to the map and skip the challenge, you'll be able to move forward.
I'm sure they'll fix the bug soon

**Comment by morgynbh** [comment]
I'm having the same issue - I entered the correct hexadecimal code for dodger blue (and all the other colors) but keep receiving an error message for that one component.

**Comment by bbojan7** [comment]
Same issue here, all color tasks ara marked as done, just task for dodger blue is marked as wrong.

**Comment by jbradshaw4** [comment]
Apparently - it's an actual issue and not the code- it's been recommended to move on to the next challenge until it's resolved.

**Comment by ChloeB123** [comment]
Hey guys, just to give you a heads up, I'm still having this problem as well

**Comment by erictleung** [comment]
@ChloeB123 this is [resolved in the codebase](https://github.com/freeCodeCamp/freeCodeCamp/blob/d424b7331ded350e297387b134f5ab8e85631839/seed/challenges/01-responsive-web-design/basic-css.json#L3196), it just hasn't been pushed to the production site. In the meantime, just use the code found in the table description. But if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by davidstulajter** [comment]
Still no luck, it is not working. #1E90FF still does not work.

**Comment by lizaiueo** [comment]
<style>
  .red-text {
    color: #FF0000;
  }
  .green-text {
    color: #00FF00;
  }
  .dodger-blue-text {
    color: #1E90FF;
  }
  .orange-text {
    color: #FFA500;
  }
</style>

<h1 class="red-text" style="color: rgb(255, 0, 0)">I am Red!</h1>

<h1 class="green-text" style="color: rgb(0, 255, 0)">I am Green!</h1>

<h1 class="dodger-blue-text" style="color: rgb(30, 144, 255)">I am dodger blue!</h1>

<h1 class="orange-text" style="color: rgb(255,165,0)">I am orange!</h1>

**Comment by RandellDawson** [comment]
@davidstulajter Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.
