### ISSUE TITLE
Iterate over Array with .map Issue! FIXED by FCC

### ISSUE THREAD

**Issue by baohien97** [FreeCodeCamp/FreeCodeCamp#10548]
Challenge [iterate-over-arrays-with-map](https://www.freecodecamp.com/en/challenges/object-oriented-and-functional-programming/iterate-over-arrays-with-map) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code is as followed but I keep getting "You should only modify arrays with map"! Please could you have a look into this?
![iteratemap](https://cloud.githubusercontent.com/assets/20854375/18381238/979ded44-767b-11e6-9dcd-85b353d3bbcd.PNG)

```js
     
     

var oldArray = [1,2,3,4,5];

// Only change code below this line.

var newArray = oldArray.map(function(num){
return num + 3;
});

                          

     ```

**Comment by ZebraLan** [comment]
Having the same issue here.

**Comment by rungol** [comment]
Having the same problem.

**Comment by atjonathan** [comment]
This has been fixed.

**Comment by tyrolCoder** [comment]
hm. just checked and the issue is still there; are we missing something?

**Comment by graysage** [comment]
hasn't been fixed, still does not pass. oct 4 2016.

**Comment by janchen85** [comment]
Still not working, won't pass the test
