### ISSUE TITLE
Correct but not passing

### ISSUE THREAD

**Issue by c-s-avage** [FreeCodeCamp/FreeCodeCamp#10580]
Challenge [manipulating-complex-objects](https://www.freecodecamp.com/en/challenges/basic-javascript/manipulating-complex-objects) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js
    \ file: 
var myMusic = [
{
  "artist": "Billy Joel",
  "title": "Piano Man",
  "release_year": 1973,
  "formats": [ 
    "CS", 
    "8T", 
    "LP" ],
  "gold": true
}
// Add record here
];


    
var myMusic = [
{
  "artist": "Billy Joel",
  "title": "Piano Man",
  "release_year": 1973,
  "formats": [ 
    "CS", 
    "8T", 
    "LP" ],
  "gold": true
}
// Add record here
];


    ```
    
```html
    \ file: 
var myMusic = [
{
  "artist": "Billy Joel",
  "title": "Piano Man",
  "release_year": 1973,
  "formats": [ 
    "CS", 
    "8T", 
    "LP" ],
  "gold": true
},
// Add record here
  {
  artist: "Pink Floyd",
  title: "The Wall",
  release_year: 1982,
  formats: [
    "LP",
    "Cassette"
  ]
}
];


    
var myMusic = [
{
  "artist": "Billy Joel",
  "title": "Piano Man",
  "release_year": 1973,
  "formats": [ 
    "CS", 
    "8T", 
    "LP" ],
  "gold": true
},
// Add record here
  {
  artist: "Pink Floyd",
  title: "The Wall",
  release_year: 1982,
  formats: [
    "LP",
    "Cassette"
  ]
}
];


    ```

**Comment by c-s-avage** [comment]
My code is correct but it's not passing.
![image](https://cloud.githubusercontent.com/assets/20207187/18390215/41251ba8-7677-11e6-94bc-77657c63d1f8.png)

**Comment by c-s-avage** [comment]
I was missing the quotation marks in the second object.  however, even after fixing it is still not passing.
![image](https://cloud.githubusercontent.com/assets/20207187/18390331/c6bf08fa-7677-11e6-9926-c5da6a8f7982.png)

**Comment by Cerberus360** [comment]
var myMusic = [
  {
    "artist": "Billy Joel",
    "title": "Piano Man",
    "release_year": 1973,
    "formats": (
      "CS",
      "8T",
      "LP"
    ),
    "gold": true
  },
  // Add record here
  {
    "artist": "Pink Floyd",
    "title": "The Wall",
    "release_year": 1982,
    "formats": (
      "LP",
      "Cassette"
    )
  }
]

**Comment by Cerberus360** [comment]
fixed :)

**Comment by c-s-avage** [comment]
It is still not passing for me.  I'm confused.  Is this a bug or am I doing something incorrectly?

**Comment by Cerberus360** [comment]
hmmm, see I tried this on my codepen account and it worked, so I could call on the objects, could be a bug

**Comment by dhcodes** [comment]
@c-s-avage In this case, I believe you have a couple errors in your code. I tested the corrected code in Firefox and Chrome and both passed. Consider asking for help in the [Help Chat](https://gitter.im/FreeCodeCamp/Help) room for FreeCodeCamp.

**Comment by Cerberus360** [comment]
For the record it might be beneficial to read up on JSON.

On 9 Sep 2016 16:37, "c-s-avage" <notifications@github.com> wrote:

It is still not passing for me. I'm confused. Is this a bug or am I doing
something incorrectly?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10580#issuecomment-245949382>,
or mute the thread

**Comment by h2ppy** [comment]
it is bug

**Comment by c-s-avage** [comment]
This is working for me now.
