### ISSUE TITLE
'Update your settings' redirects to /map

### ISSUE THREAD

**Issue by Bouncey** [FreeCodeCamp/FreeCodeCamp#10879]
#### Issue Description

When viewing my public profile, if I click `Update your settings` I am directed to `/map`

**Comment by dhcodes** [comment]
Confirmed. The routes are correct so I'm guessing it's something to do with the user-check functionality of this: https://github.com/FreeCodeCamp/FreeCodeCamp/blob/914e9f4b337724a5f4a24ebcfdf67058c7b0367e/common/app/routes/settings/index.js#L13

**Comment by Bouncey** [comment]
Hmmm user must be undefined...

**Comment by Bouncey** [comment]
I've just had a quick play around with this, but to be honest I'm shooting from the hip, in the dark, blindfolded!

Things I learnt:
* `user` is indeed undefined when that module is read
* Nav bar profile picture and brownie points are not rendered at the time of 'user' being read

Could this be an async issue? @BerkeleyTrue

**Comment by Bouncey** [comment]
I have just seen this whilst QA'ing a PR.

When I clicked `Update my profile from github` this appeared in the shell:

```sh
302 GET 42174.522 ms - /link/github
  fcc:userIdent link identity query +4m { where: { provider: 'github', externalId: '18572518' } }
  fcc:models:userIdent picture +6s https://avatars.githubusercontent.com/u/18572518?v=3 https://avatars.githubusercontent.com/u/18572518?v=3
  fcc:models:userIdent user isn't github cool or username from github is different +32ms
302 GET 31171.534 ms - /auth/github/callback/link?code=be64b48d523f77baed4e
302 GET 7908.538 ms - /en/
200 GET 41927.823 ms - /en/bouncey
  fcc:react-server react router found a redirect +55s
302 GET 742.300 ms - /en/settings
  fcc:react-server render react markup and pre-fetch data +534ms
  fcc:services:map en language requested +116ms
  fcc:react-server react markup rendered, data fetched +5s
  fcc:react-server html rendered and ready to send +2s
200 GET 6681.452 ms - /en/map
  fcc:services:user user is signed in +22s
200 GET 199.021 ms - /services/user?_csrf=HM86w3rs-v42Lr2BNQPmCja6M2aDOcGQbs6w&returnMeta=true
```

It's getting as far as rendering the setting page, but then redirects to map when it hits `if (!user)`

Only after arriving at map am I declared to be signed in.

**Comment by ivantedja** [comment]
It seems that `user` is defined only if we are within react app. `/username` has not been converted into react so `user` is undefined. It can be replicated via `/about` as well (not react-ed yet). Whereas it should work fine if `/settings` accessed from:
- `/challenges`
- `/map`
- `/settings` itself

**Comment by systimotic** [comment]
Was this fixed somewhere? https://github.com/FreeCodeCamp/FreeCodeCamp/pull/10824#issuecomment-253985467

**Comment by atjonathan** [comment]
Yeah, this has been resolved in staging. Thanks for bringing this to our attention @systimotic 😜

**Comment by ivantedja** [comment]
@atjonathan which commit resolve this one?

**Comment by atjonathan** [comment]
@ivantedja, not sure. Check the `staging` branch. I believe it was fixed accidentally!

**Comment by ivantedja** [comment]
@atjonathan lol thanks

**Comment by systimotic** [comment]
I've been trying to solve #10802 today. I'm not sure if I'll be able to do it, but I during my experimentation I found that this issue still seems to be present. If you visit any protected route from a non-React route (whether that's FreeCodeCamp itself or a link from a different site) you get redirected to the map. An issue way to replicate this issue is (given you're logged in) going to the shop, then clicking on the right most item in the nav, which is supposed to redirect you to your settings. It will redirect you to the map.

**Comment by BerkeleyTrue** [comment]
navigating directly to /settings will redirect to map. I'm currently working on a shadow settings page to wait for user data to be loaded. At that point the page will load directly.
