### ISSUE TITLE
Bug Issue on Uncomment HTML

### ISSUE THREAD

**Issue by keesas** [FreeCodeCamp/FreeCodeCamp#1158]
Challenge http://www.freecodecamp.com/challenges/waypoint-uncomment-html has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Below is link to screen. Issue is that even after deleting the --> that ends the comment, I am not allowed to go to my next challenge

![image](https://cloud.githubusercontent.com/assets/13089821/8421624/858ec130-1e9f-11e5-9863-9230ac98a428.png)
Uncomment HTML
Uncomment your h1, h2 and p elements.

Commenting is a way that you can leave comments within your code without affecting the code itself.

Commenting is also a convenient way to make code inactive without having to delete it entirely.

You can start a comment with .

Less information

Go to my next challenge
(ctrl + enter)
  Help	  Bug
 Make your h1 element visible on your page by uncommenting it.
 Make your h2 element visible on your page by uncommenting it.
 Make your p element visible on your page by uncommenting it.
Be sure to delete the --> that ends the comment.

1

4
<h2>CatPhotoApp</h2>
5

8
<p>Hello Paragraph</p>

**Comment by LumenTeun** [comment]
The problem is that you still have a few comments, `<!-->`, in your code, and the test cases check to make sure you don't have any trailing comment tags, `-->` in there. I'll submit a PR in a second that slightly alters the words used in the waypoint, but I'm not sure it should be necessary.

**Comment by keesas** [comment]
Thx Lumen! Just so I'm clear, I need to delete ' <!--> ' all throughout the code?

**Comment by LumenTeun** [comment]
@keesas Exactly :)

**Comment by benschenker** [comment]
Fixed in #1160

**Comment by SevenSector7** [comment]
I did delete ' <!--> ' all through the code and I'm STILL having issues. And I'm new to this so pardon my slowness to understanding plz.
