### ISSUE TITLE
Bonfire: Return Largest Numbers in Arrays

### ISSUE THREAD

**Issue by juliuslove** [FreeCodeCamp/FreeCodeCamp#1228]
The test arrays don't contain the expected results causing the code to fail.

From basic-bonfires.json

```js
 "tests": [
        "expect(largestOfFour([[4, 5, 1, 3], [13, 27, 18, 26], [32, 35, 37, 39], [1000, 1001, 857, 1]])).to.be.a('array');",
        "(largestOfFour([[4, 5, 1, 3], [13, 27, 18, 26], [32, 35, 37, 39], [1000, 1001, 857, 1]])).should.eql([5,27,39,1001]);",
        "assert(largestOfFour([[4, 9, 1, 3], [13, 35, 18, 26], [32, 35, 97, 39], [1000000, 1001, 857, 1]]).should.eql([9,35,97,1000000]));"
      ],
```

**Comment by carl-parrish** [comment]
I'm not understanding what you're saying the problem is here. Can you explain or close it?

**Comment by BerkeleyTrue** [comment]
@juliuslove Thanks for reporting this. Indeed it just needs the function call for the second test.

**Comment by juliuslove** [comment]
The issue I was originally having seemed to have worked itself out.  My code hadn't actually changed but I was able to get the test to pass just now.  I copy and pasted my saved code in and it worked as it should have so my issue is resolved.  I am going to close this ticket as the bonfire appears to be working.

Thanks.

**Comment by Ikucuk** [comment]
I still have an issue on this.
My code passed the first two, but fails on the third.
If I replace the default code with the array from the last one, the second one fails.

If I remove "return arr;" from the code altogether, it passes.

**Comment by BerkeleyTrue** [comment]
closing as stale. Please feel free to reopen if issue still persists.
