### ISSUE TITLE
"Session and Cookie" exercise missing from ExpressWorks.

### ISSUE THREAD

**Issue by ug02fast** [FreeCodeCamp/FreeCodeCamp#1449]
Challenge http://www.freecodecamp.com/challenges/waypoint-build-web-apps-with-express.js has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Image shows exercises available. "Complete "Session and Cookie"" from the FCC page isn't available in the Expressworks exercises.

![bugexpressworks](https://cloud.githubusercontent.com/assets/5507707/9023572/b7c43d04-3855-11e5-9b49-e6454f388007.png)

**Comment by ahstro** [comment]
This was fixed in #1368, but not merged in favor of #1369 which doesn't seem to address the issue at all... so, yeah.. I'll let @SaintPeter fix this? :)

**Comment by IgnacioCorto** [comment]
"Session and Cookie" is still present here: http://freecodecamp.com/challenges/waypoint-build-web-apps-with-expressjs

Meanwhile, I will mark this waypoint as completed.

**Comment by BerkeleyTrue** [comment]
closing as stale. Please feel free to reopen if issue still persists.
