### ISSUE TITLE
 Using "-" in the "alt" attribute does not complete the "must have an alt attribute" challenge

### ISSUE THREAD

**Issue by wikidude** [freeCodeCamp/freeCodeCamp#14926]
Challenge [Add Images to your Website](https://www.freecodecamp.com/challenges/add-images-to-your-website) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

# Using "-" in the "alt" attribute text does not complete the "Your image must have an alt attribute" challenge

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>
<img src="https://bit.ly/fcc-relaxing-cat" alt="Upside-Down Kitten.">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by dhcodes** [comment]
@wikidude thanks for the issue, but this is resolved in beta.

**Comment by tr2000** [comment]
The problem persists - my alt statement fails:
alt="YACP - Yet another cat picture"

**Comment by evansampson** [comment]
Issue still occurs when using '-' in my alt statement:
<img src="https://bit.ly/fcc-relaxing-cat"
alt= "Upside-down cat.">

**Comment by dhcodes** [comment]
Locking this conversation as this issue is resolved on beta and will be corrected when beta curriculum is added to the main site.
