### ISSUE TITLE
"Clone-an-element-using-jquery" maybe have some problem.

### ISSUE THREAD

**Issue by shifengchen** [freeCodeCamp/freeCodeCamp#15010]
Challenge [Clone an Element Using jQuery](https://www.freecodecamp.com/challenges/clone-an-element-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

## When I click the "Run test", there are two "#target5" button in phone screen.

My code:
```html

<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target4").remove();
    $("#target2").appendTo("#right-well");
    $("#target5").clone().appendTo("#left-well")
  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by dhcodes** [comment]
this is fixed in beta

**Comment by damjem** [comment]
I have found the same bug on firefox browser.

**Comment by MurdockBlue7** [comment]
Using firefox, I've also discovered the same issue.

**Comment by dhcodes** [comment]
this is fixed in beta

**Comment by abdoullfurya** [comment]
Using chrome and its still not working

**Comment by PhinFin** [comment]
It's still not working in Firefox.  How do I move to the next challenge?

**Comment by shifengchen** [comment]
@PhinFin Just go ahead, it's an insignificant bug.
