### ISSUE TITLE
Smallest Common Multiple -- add a note about // noprotect

### ISSUE THREAD

**Issue by azurvii** [freeCodeCamp/freeCodeCamp#15819]
#### Challenge Name
https://www.freecodecamp.org/challenges/smallest-common-multiple
#### Issue Description
My code failed the last test, but passed with `// noprotect` in the top. I figured it out when reading [this post](https://forum.freecodecamp.org/t/smallest-common-multiple-need-help/134828/6).
My suggestion is to add a line in the description about `// noprotect`. Or to update the error message to ask people to make a more efficient algorithm. Otherwise people make inefficient algorithms like mine would be quite confused why it does not pass.

Thanks!

**Comment by w96k** [comment]
Nice idea, I had this problem too.

**Comment by systimotic** [comment]
@azurvii @w96k Can you share your solutions? I'm curious to see why this went the way it did.

**Comment by azurvii** [comment]
(This)[https://www.freecodecamp.org/challenges/Smallest%20Common%20Multiple?solution=%2F%2F%20noprotect%0A%2F%2F%20const%20MAX_ROUNDS%20%3D%2010000000%3B%0A%0Afunction%20isCommonMultiple(num%2C%20min%2C%20max)%20%7B%0A%20%20var%20result%20%3D%20true%3B%0A%20%20for%20(var%20i%20%3D%20min%3B%20i%20%3C%3D%20max%3B%20%2B%2Bi)%20%7B%0A%20%20%20%20if%20(num%20%25%20i%20!%3D%200)%20%7B%0A%20%20%20%20%20%20result%20%3D%20false%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20result%3B%0A%7D%0A%0Afunction%20smallestCommons(arr)%20%7B%0A%20%20var%20max%20%3D%20Math.max.apply(null%2C%20arr)%3B%0A%20%20var%20min%20%3D%20Math.min.apply(null%2C%20arr)%3B%0A%20%20var%20i%20%3D%20max%3B%0A%2F%2F%20%20%20var%20ceiling%20%3D%20max%20%2B%20MAX_ROUNDS%3B%0A%20%20while%20(true)%20%7B%0A%20%20%20%20if%20(isCommonMultiple(i%2C%20min%2C%20max))%20%7B%0A%20%20%20%20%20%20return%20i%3B%0A%20%20%20%20%7D%0A%20%20%20%20%2B%2Bi%3B%0A%20%20%7D%0A%2F%2F%20%20%20return%20undefined%3B%0A%7D%0A%0A%0AsmallestCommons(%5B1%2C5%5D)%3B%0A%0A] was my solution. This fails the last test on my Safari/iOS, Safari/macOS, Chromium/Xubuntu. And it fails last 2 tests on my Firefox/Xubuntu. The URL contains 'noprotect' in the query string, but it apparently got stripped out when displayed in the editor.

**Comment by systimotic** [comment]
Thanks @azurvii! This is indeed an issue. At the very least, there should be a warning here.
I'm putting the code directly in this issue for future reference
```js
function isCommonMultiple(num, min, max) {
  var result = true;
  for (var i = min; i <= max; ++i) {
    if (num % i != 0) {
      result = false;
      break;
    }
  }
  return result;
}

function smallestCommons(arr) {
  var max = Math.max.apply(null, arr);
  var min = Math.min.apply(null, arr);
  var i = max;

  while (true) {
    if (isCommonMultiple(i, min, max)) {
      return i;
    }
    ++i;
  }
}
```

**Comment by xjlim** [comment]
I will work on this

**Comment by sw-yx** [comment]
i take it this is solved?

**Comment by idietmoran** [comment]
This is not solved. I failed with this code until i put the `// noprotect` flag in

```js
function smallestCommons(arr) {
    arr.sort();

    let greatestNum = arr[arr.length - 1];

    while(true) {

        let isMultiple = true;

        for(let i = arr[0]; i < arr[arr.length - 1]; i++) {
            if(greatestNum % i !== 0) {
                isMultiple = false;
            }
        }

        if(isMultiple)
            return greatestNum;

        greatestNum += arr[arr.length - 1];
    }
}

console.log(smallestCommons([1, 5]));   // 60
console.log(smallestCommons([5, 1]));   // 60
console.log(smallestCommons([1, 13]));  // 360360
console.log(smallestCommons([23, 18])); // 6056820
```

**Comment by QuincyLarson** [comment]
@Greenheart Can you verify whether this is still a problem on the newly-launched platform? If so, do you have any ideas for how to fix it?

**Comment by mpisters** [comment]
I have also this issue with my code (not very optimised):

```function smallestCommons(arr){
    const par1 = arr[0];
    const par2 = arr[1];
    let isDividable = false;
    let range = false;
    let number = 1;
    while(!isDividable){
        let diff1 = number % par1;
        let diff2 = number % par2;
        if (number % par1 === 0 && number % par2 === 0 && diff1 === diff2 ){
            const start = par1 >= par2 ? par2 : par1;
            const end = par1 >= par2 ? par1 : par2;
            for(let i = start; i < end; i++){
                if (number % i === diff1){
                    range = true;
                } else {
                    range = false;
                    break;
                }
            }
            if (range){
               isDividable = true;
            }
        }
        number++;
    }
    return number - 1;
}

console.log("does it work?", smallestCommons([23,18]));```

When I run this in the chrome browser it works, but in freecodecamp it doesn't. I also added // no protect but doesn't seem to work.

**Comment by charlottetan** [comment]
I'm not able to reproduce the issue with the code snippets in this thread, this issue can probably be closed.
