### ISSUE TITLE
[beta] Add React and Redux challenges to seed directory once they're working

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#16115]

**Comment by BerkeleyTrue** [comment]
@no-stack-dub-sack 

> This screencast shows an example: http://recordit.co/zdtNznADl2. This challenge definitely worked before, so the tests are good, but when you run the solution, the tests still fail. When you refresh, it says it's loading saved work, but it still just loads the seed again. I've done some logging to investigate further on failing tests, and what it seems is that the edited code is never actually being evaluated or saved to local storage. So at the moment, we're unable to verify that our new tests actually work.

The error indicates the process that takes the content of the editor and updates the appropriate section in redux. It seems like this part may have a bug. I'll take a look and see if I can track it down.

> We can still test challenges with `npm test`, but that feedback loop is very slow, and we've noticed that not all challenges that pass the automated test suite pass in the browser. 

Yes, the test suite is insufficient. We are hoping to change this in the future to use the same modules that the browser uses. I believe @raisedadead was looking into this.

**Comment by bonham000** [comment]
The other two things the challenges will need at this point are availability of original, un-transpiled code and mock document in the test environment.

If we can provide `editor.getOriginalCode()` that would be great because that's how we are converting those tests now.

The other is availability of a `document` within the test environment for the ReactDOM challenges.

**Comment by raisedadead** [comment]
Yes, I have been trying to research and integrate this.

And just to note, I think https://github.com/ternjs/acorn and some of the community plugins (for react) should give us the necessary base to build up on.

**Comment by raisedadead** [comment]
Of course, with Karma (a test runner) and any compatible testing library that we choose, we should have them tested in browser (even in CI environment) too.

**Comment by bonham000** [comment]
We are also seeing very strange results with `npm test`, e.g.

<img width="488" alt="failure" src="https://user-images.githubusercontent.com/18126719/33852302-d5a31694-de6e-11e7-8400-07ce9aa2d18e.png">

which occurs even though all of our individual tests that we add pass.

**Comment by BerkeleyTrue** [comment]
@bonham000 yes, this is an issue that rears its head from time to time but I have not been able to track down.

**Comment by BerkeleyTrue** [comment]
@bonham000 @no-stack-dub-sack I've got a pr that should fix the issue in the video. Mind giving it a test/merge?

**Comment by bonham000** [comment]
@BerkeleyTrue this seems to help and resolve the previous error. It's easier to test solutions against challenges now. However, the app still doesn't seem to be working completely. I still have to clear local storage and challenges do not seem to always update when I change the code.

Also, it seems like the `tail` code is not being applied in the editor before the test are run.

**Comment by bonham000** [comment]
Also, there are problems with the preview pane for the React challenges.

Not all the challenges create components with the same name. If the preview is trying to render a component, .e.g. `MyComponent` somewhere, it will only work if the challenges has a component with that name, which is not all of them.

**Comment by BerkeleyTrue** [comment]
> Not all the challenges create components with the same name. If the preview is trying to render a component, .e.g. MyComponent somewhere, it will only work if the challenge has a component with that name, which is not all of them.
I don't understand this statement. Can you clarify?

**Comment by BerkeleyTrue** [comment]
@no-stack-dub-sack and @bonham000 

We just landed two PR's that should improve the process. 

The first is the issue with the editor not updating code.

The second one fixes the issue of sourcing the original user code.

The next bit that I'll be working on is getting the react components to render in the preview. It seems we need multiple files for this. The user code and an html code to render react to. As a stop gap, I'll add a template property to the challenge spec that will be used to populate the iframe before user code. 

Let me know how this sounds.

**Comment by bonham000** [comment]
@BerkeleyTrue this sounds great we'll check out the updates from the PRs soon.

About preview, what I meant is that in each challenge we have which previews React code we take the root component in that challenge and render it to a DOM node in our page using ReactDOM to create the preview. This requires us to know the name of the root React component, which is not the same in all the challenges (e.g. `JSX`, `MyComponent`, `AppWrapper`, etc.). This name is hardcoded in the tests files for each challenge and used for the preview.

Also, for that to work it would need any `head` and `tail` code transpiled along with the user's code. This is also true for the tests themselves, and we've noticed it seems the `head` and `tail` code is not being provided when the tests are executed. We would need it and it would need to be transpiled along with the user's code for our tests.

**Comment by BerkeleyTrue** [comment]
> This requires us to know the name of the root React component, which is not the same in all the challenges

This would be handled in the head/tail code

>Also, for that to work it would need any head and tail code transpiled along with the user's code. 

Hmmm, this should be a simple enough addition

> we've noticed it seems the head and tail code is not being provided when the tests are executed

Do you mean it is not being added to the code or that you need access to the head/tail string outside of the eval?

**Comment by BerkeleyTrue** [comment]
code links/examples would probably clear up the confusion quicker

**Comment by bonham000** [comment]
@BerkeleyTrue the main thing we thought we saw is that the head tail code was not present around the user's code when the tests were executed, or at the very least if it was there it wasn't transpiled.

If we can agree on a name for the component to be preview rendered, e.g. `PreviewComponent`, we can add this to the `tail` code for all the challenges and assign it to the appropriate component for the challenge. Let us know.

**Comment by BerkeleyTrue** [comment]
>  if it was there it wasn't transpiled.

I believe this is most likely. 

> if we can agree on a name for the component to be preview rendered

The way it's implemented this should be completed controlled from the seed definition.

**Comment by QuincyLarson** [comment]
@BerkeleyTrue Just merged #16200 and these are now in staging! Woo-hoo! Thanks everyone!
