### ISSUE TITLE
ES6:  Use the Rest Operator with Function Parameters - spread operator test fails

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16351]
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/es6/use-the-rest-operator-with-function-parameters

#### Issue Description

The challenge fails on the last test "The sum function uses the ... spread operator on the args parameter.
I have tripled checked my code, reset it and refreshed but it doesn't seem to recognize the spread operator is being used. 

I found this but not sure if related:
Reference: https://github.com/freeCodeCamp/freeCodeCamp/issues/12698

#### Browser Information

Browser Name, Version:
Operating System: FireFox 57.0 (64-bit) and Chrome Version 63.0.3239.84 (Official Build) (64-bit)
Mobile, Desktop, or Tablet: Laptop Windows 10 Professional 64-bit

#### Your Code

```js

`"use strict()";
function sum(...array) {
    return array.reduce((a, b) => a + b, 0);
}
console.log(sum(1, 2, 3)); // 6`

```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/34400833-4ab6103e-eb63-11e7-94f7-3ca6b87cf096.png)

**Comment by mstellaluna** [comment]
Nevermind its my fault :)

**Comment by systimotic** [comment]
@mstellaluna I don't think this is your fault. The challenge expects the argument to be named `args`, but it doesn't mention that in the instruction. The instruction should be updated to say that you need to name the parameter `args`

**Comment by sagarjhaa** [comment]
Can I work on it ?

**Comment by theoutlander** [comment]
@sagarjhaa Put a note here and go for it

**Comment by sagarjhaa** [comment]
Working on this bug. Thanks @theoutlander

**Comment by theoutlander** [comment]
I feel like this shouldn't be a bug because it forces the user to think a bit more about the question. It appears pretty clear from the question when it says **spread operator on the args** parameter.

**Comment by sagarjhaa** [comment]
@theoutlander this has happened to me before, that using any other variable to solve the problem will not complete the challenge even when the logic is right. Should we let user use any variable name or hint them to use only **args**

**Comment by theoutlander** [comment]
I feel that users should be reading the question. However, if you wrote code that compiles, it should pass. So, I think this needs to be fixed.... but, my thought was that people are making a mistake because they're not reading the question (perhaps, the question needs improvement). IMO, it's one of those lessons about reading the requirements.

**Comment by sagarjhaa** [comment]
I agree to your question reading point @theoutlander. The last validation also indicates that we are expecting **args** variable in the solution. **The sum function uses the ... spread operator on the args parameter.**

Let me know if we need to fix it.

**Comment by theoutlander** [comment]
I think the fix is easy, so let's do it. @QuincyLarson do you have a preference? We could go either way on this one.

**Comment by systimotic** [comment]
@theoutlander I do agree that reading the question is important, but I think the issue here is that it's not mentioned at all in the initial instructions. It does show in the tests, but the test states it as if it should already have been obvious.

I think the best fix for this is renaming `array` in the seed code (the code that is in the editor when you open the page) to `args`. @sagarjhaa Do you want to take this on?

**Comment by sagarjhaa** [comment]
On it. Thanks @systimotic

**Comment by raisedadead** [comment]
@sagarjhaa are you still working on this?

**Comment by sagarjhaa** [comment]
@raisedadead I got into an issue while doing a PR. I have fixed it on my local. I will try to do a pull request right now. Might need help as this is my second PR.

**Comment by raisedadead** [comment]
@sagarjhaa sure, good luck. If you need any assistance please reach us in the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors)

**Comment by PolarisTLX** [comment]
Just ran into this. I agree this test should not fail if you can pass all the expected output tests. Or it should be clearer what is meant, because I still cannot figure out what the last test wants to get the last check to pass.

**Comment by raisedadead** [comment]
@PolarisTLX can you please start a fresh thread by creating a new issue.

**Comment by zohaib9613** [comment]
It still has the same problem.
