### ISSUE TITLE
My account profile wont go public and I can’t turn night mode off…

### ISSUE THREAD

**Issue by micqey** [freeCodeCamp/freeCodeCamp#17551]
Hey there camp counselors!

I think I may be having some account conflicts… :-/

My account profile wont go public and I can’t turn night mode off…

Also I completed the Javascript Cert, but I don’t see a link to it anywhere…

The email for this forum account is not the same as the account I am having issues with, but I’m not sure I want to try and update because I don’t want to create any more conflicts.

A couple of days ago I decided to abandon the account associated with this email, and changed the names on the two learn.fcc accounts so that I could have my old username on the new account.

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 65.0.3325.181
* Operating System: Mac OSX 10:11:6

**Comment by johnkennedy9147** [comment]
@micqey I think you are describing the same as #17278 which has today had a fix completed.  Once the fix gets put to the production servers this should be resolved.

**Comment by raisedadead** [comment]
The fix was deployed just minutes ago. Can you please check again with a hard refresh?

**Comment by micqey** [comment]
I did a hard refresh, but I still can't get the "Make my profile public" switch to move, and the night mode button does nothing. Also, (and most importantly) none of my solutions are available when I go back to the pages for items I've completed on the curriculum. My private bio preview has 541 points but the public bio shows 0 points... it's a little worrying...

**Comment by micqey** [comment]
I'm getting the same error that has been reported elsewhere on the settings page:
<img width="777" alt="screen shot 2018-06-12 at 1 04 16 pm" src="https://user-images.githubusercontent.com/29188860/41311350-44d01dac-6e41-11e8-903f-b0f41f3e6c4e.png">

**Comment by johnkennedy9147** [comment]
@micqey Could you clarify the following:
- On the settings page do you see the certificates section between `Academic Honesty Policy` and `Danger Zone`?
 - When you say you completed the Javascript cert do you mean you completed the 5 required projects, or that you claimed the certificate?
- Does the `Download all your data` button work? If so could you download your data and inspect the completed challenges section for the following ids.

``` json
"id": "aaa48de84e1ecc7c742e1124",
"title": "Palindrome Checker",

"id": "a7f4d8f2483413a6ce226cac",
"title": "Roman Numeral Converter",

"id": "56533eb9ac21ba0edf2244e2",
"title": "Caesars Cipher",

"id": "aff0395860f5d3034dc0bfc9",
"title": "Telephone Number Validator",

"id": "aa2e6f85cab2ab736c9a9b24",
"title": "Cash Register",
```

Do you see entries with `null` entries like below?
![image](https://user-images.githubusercontent.com/26827682/41319027-610a2ba6-6e92-11e8-8a48-b9b4f47bde14.png)

**Comment by micqey** [comment]
I do see the certificates section, and I completed the challenges and projects, but never claimed the certificate. Also I downloded "all my data" but it's empty... everything is null...

I literally went through everything in the Javascript section. Does this mean it's all gone?

**Comment by micqey** [comment]
Every line looks like this:
`{"id":"bad87fee1348bd9aedf08802","completedDate":1528044361849,"solution":null,"challengeType":null,"files":[]},`

**Comment by johnkennedy9147** [comment]
@micqey Hi, we are not storing solutions for challenges any more, just storing solutions for projects, but there was an issue which affected these JS projects causing them to not be stored.  That issue was fixed yesterday. But there still needs to be a database update for affected users, but as a workaround if you resubmit your 5 JS projects the solutions should now be stored and you can claim the certificate.

Regarding the buttons not working, everyone I know of affected by that issue found the buttons started working again at the same time as the sections reappeared.

Could you add screenshots of the whole privacy section from the settings page and the `profileUI` section  from the downloaded data.

Might be a good idea to clear cookies for the site, then login again and see if your symptoms are still the same.

**Comment by JMVL64** [comment]
For me it is solved! i do have to fill in my javascript challenges again, but everything works. Thanks so much!

**Comment by raisedadead** [comment]
Hi @micqey can you please connect with me over email, I'll try and check this: `mrugesh at freecodecamp dot org`

**Comment by micqey** [comment]
I think I'm good to go. I just need to re-do the javascript projects because it didn't save my solutions.  I was also able to update my profile to public and switch from night mode to regular. 
Thanks for all the help!

**Comment by raisedadead** [comment]
Awesome.. thanks for letting us know. and apologies about the issues.

**Comment by JMVL64** [comment]
One question on the night theme. Is it correct that the night theme has not been implemented yet in the curriculum?

**Comment by micqey** [comment]
I don’t know about the implementation of night theme, my issue was simply
that I couldn’t move the switch to change it on the profile. That issue is
fixed for me, but my guess is that the night theme implementation has its
own thread with more relevant information.

**Comment by johnkennedy9147** [comment]
@JMVL64 Night mode is not presently available on the Learn platform (curriculum).
Quincy mentioned it in his announcement - "Night Mode doesn’t work on the learning platform yet. We’re working on fixing this."
https://forum.freecodecamp.org/t/10-major-freecodecamp-improvements-that-are-live-now/192130

**Comment by raisedadead** [comment]
> One question on the night theme. Is it correct that the night theme has not been implemented yet in the curriculum?

Yes, that is correct. Since the launch some of the UI features were lost. We are working toward making this available soon.
