### ISSUE TITLE
Apis and Microservices Projects - Timestamp Microservice - requires both glitch and github url

### ISSUE THREAD

**Issue by P1xt** [freeCodeCamp/freeCodeCamp#17589]
#### Describe your problem and - if possible - how to reproduce it
This issue exists for all the Apis and Microservices Projects

The instructions state to use glitch OR github. But, both glitch AND github fields are required.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/apis-and-microservices/apis-and-microservices-projects/timestamp-microservice
https://learn.freecodecamp.org/apis-and-microservices/apis-and-microservices-projects/request-header-parser-microservice
https://learn.freecodecamp.org/apis-and-microservices/apis-and-microservices-projects/url-shortener-microservice
https://learn.freecodecamp.org/apis-and-microservices/apis-and-microservices-projects/exercise-tracker
https://learn.freecodecamp.org/apis-and-microservices/apis-and-microservices-projects/file-metadata-microservice

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 66.0.3359.181 (Official Build) (64-bit)
* Operating System: Manjaro 17.1.10

#### If possible, add a screenshot here

![microservices](https://user-images.githubusercontent.com/322175/41441357-e55b4640-6ff7-11e8-9c1e-4c14543ba33d.png)

**Comment by JKorhonen** [comment]
I think this isn't bug but misunderstanding. You need give link for solution (that can be outside of Glitch) and link for GitHub repository that have your solutions source code.

**Comment by anku255** [comment]
@P1xt I agree with @JKorhonen. It asks for a link of solution (where you project is hosted) and Github link (for the source code). It encourages campers to put their project on Github which is nice in my opinion.

**Comment by moT01** [comment]
Glitch is not required, just a link to a working solution of your project - github, however, is required i think - so perhaps a little bit of rewording could make it more clear - I think its fine - @P1xt any suggestions?

**Comment by raditotev** [comment]
Last time I checked it was fixed. There is only one field now - Solution.

**Comment by moT01** [comment]
still shows two fields for me when I click any of the links above

**Comment by raditotev** [comment]
You're right @moT01. Still two input fields for the final projects. It was fixed for the challenges in the module though.

**Comment by anku255** [comment]
>Glitch is not required, just a link to a working solution of your project - github, however, is required I think - so perhaps a little bit of rewording could make it more clear - I think its fine - @P1xt any suggestions?

@moT01 The challenge text does say that 
> Optionally you may choose to write your project on another platform but it must be publicly visible for our testing.

I think it's already clear that Glitch is not required as long as you host it on a platform which is publicly visible for the testing.

**Comment by moT01** [comment]
@anku255 - yes, I saw that - it's clear to me glitch is not required - what I was getting at is that it's not necessarily clear that github is required, as it says you can use glitch or github

**Comment by anku255** [comment]
@moT01 Ah, I see. I am not sure why Github is required though. It doesn't even save the Github link in the settings page.

**Comment by P1xt** [comment]
The way I read the challenge, you can either use glitch via the provided link, OR you can use the github link, clone the repo, and host the project wherever you want. It says nothing about "if you do this on glitch you need to download your project from glitch, create a github repo, push your glitch code into that repo, then submit both the glitch and github links.

I'm perfectly fine with "clone this on github, write your code, deploy your code wherever you want, then link both your github and live version". My point is that that is not what the challenge says.

**Comment by moT01** [comment]
Perhaps the place to put the github URL should be removed - Because the challenge page asks for two URL's (live demo + github), but in the settings area you can turn in any of the projects with just the live demo link

**Comment by JuanjoA** [comment]
Same here, it's not clear and demands the link to github.

**Comment by 99init** [comment]
It's not clear that both fields are required!
Also, following the other challenges, it is easily assumed that the same thing about (glitch **or** github) will apply.
imo, glitch or github should only be required since the code in glitch can be viewed using the `/edit/!#` route.

**Comment by P1xt** [comment]
I am closing this issue.

Why? Because it is an issue, the instructions are wrong - and, yet, no one has any intention of ever fixing it. Any contributor who's posted in this thread just says 'well if you do it this way, it works' when the entire point of the issue is that 'this way' is not what the instructions say to do.

And, since it's never going to get fixed - I'm sick of getting notifications every time someone posts that it's still an issue. If someone else wants to report it, create your own issue, it's sad to watch a legitimate issue just stagnate for over a year. I'm done watching it.
