### ISSUE TITLE
Test passing though the code doesn't check all test cases.

### ISSUE THREAD

**Issue by IAmRC1** [freeCodeCamp/freeCodeCamp#17734]
#### Describe your problem and - if possible - how to reproduce it
I am using this code and it is passing though I am not checking it for all users. 
while(users.hasOwnProperty("Alan")){
    return true;
  }
  return false; 

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/check-if-an-object-has-a-property

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 67.0.3396.99 (Official Build) (64-bit)
* Operating System: Windows 10

**Comment by Tirjasdyn** [comment]
it also passes with the following:

if ('Alan' in users) {
return true;
} else {
  return false;
}

Since all tests contains Alan it always passes if all you check for is Alan.

**Comment by thecodingaviator** [comment]
This has been fixed in #19390 , @RandellDawson since you had made the PR, I request you to also close the issue :)

**Comment by RandellDawson** [comment]
This is actually not resolved yet.  There is a PR #19477 which seems to be a possible fix.  I will keep this open until it has been tested, approved and merged.
