### ISSUE TITLE
Text "[object Object]" found on the Learning Map

### ISSUE THREAD

**Issue by yihyang** [FreeCodeCamp/FreeCodeCamp#1828]
![screen shot 2015-08-17 at 2 31 44 pm](https://cloud.githubusercontent.com/assets/8537324/9299268/bd16d264-44ec-11e5-9c7a-074b6099170b.png)

Hi I have found this on my Learning Map... Hope this can help you all in solving bugs... :)

**Comment by yihyang** [comment]
![screen shot 2015-08-17 at 2 48 39 pm](https://cloud.githubusercontent.com/assets/8537324/9299503/1af10dee-44ef-11e5-8233-eb72d5a56985.png)

Note: it seems to appear only on the section of lessons that I have completed.

**Comment by ahstro** [comment]
This was fixed in #1843 and can be closed.

**Comment by meecoder** [comment]
@ahstro after reloading the page, I still get this - has the fix not been pushed to the server yet?

**Comment by benmcmahon100** [comment]
It got pushed just there folks!
