### ISSUE TITLE
Account Page Loading Error (IE)

### ISSUE THREAD

**Issue by bhmann** [FreeCodeCamp/freecodecamp#20]
When loading http://www.freecodecamp.com/account in IE, it does not load properly.
![fcc bug 2](https://cloud.githubusercontent.com/assets/4038756/5709209/da211068-9a65-11e4-98e6-55dda3615bf8.png)

**Comment by terakilobyte** [comment]
Closing this issue based upon your confirmation in gitter chat it was resolved!

**Comment by bhmann** [comment]
This issue has not been resolved... IE still does not load the account page properly.

**Comment by terakilobyte** [comment]
Issue reopened

**Comment by brndnb** [comment]
What will FCC's stance be going forward on support for browsers? Do we really need to spend dev time supporting IE at this point?

**Comment by FreeCodeCamp** [comment]
I think we should try to be compatible with the current versions of IE and
Safari, in addition to edge Firefox and Chrome. I'm open to other opinions
on this. Ideally, our campers will quickly install Chrome since DevTools is
part of the curriculum.

On Thu, Jan 15, 2015 at 7:08 PM, Branden Byers <notifications@github.com>
wrote:

> What will FCC's stance be going forward on support for browsers? Do we
> really need to spend dev time supporting IE at this point?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/freecodecamp/issues/20#issuecomment-70202208>
> .
>



-- 
*Learn to Code*,
http://freecodecamp.com
Free Code Camp

**Comment by terakilobyte** [comment]
I know what's causing the issue, but am not sure why IE isn't playing well.
There is a planned update that should completely address this problem.

**Comment by QuincyLarson** [comment]
If this is a known issue specifically with IE that is likely to be solved by a forthcoming IE patch, we should close this issue.
