### ISSUE TITLE
Bogus error message

### ISSUE THREAD

**Issue by mschrauth** [FreeCodeCamp/FreeCodeCamp#2262]
![fcc generate random whole numbers within a range](https://cloud.githubusercontent.com/assets/13265618/9373792/0ff2376c-46b4-11e5-95dc-711da0298ba0.png)
Challenge http://www.freecodecamp.com/challenges/waypoint-generate-random-whole-numbers-within-a-range has an issue. Please describe how to reproduce it, and include links to screenshots if possible.  I initially used a slightly simplified version, but even with spelling it out exactly like in the directions, it keeps telling me I'm using the wrong function.

**Comment by benschenker** [comment]
Hey, thanks for posting an issue!

It looks like it wants you to use `max` and `min` as variables like in the explanation code.  It is confusing though that it asks you to make it generate a number between 0 and 9.

**Comment by dokkillo** [comment]
Hi.
Yesterday i fixed that issue, var max is equal to 9 now

**Comment by calskin** [comment]
Just jumping in here.  It's not fixed yet.  I'm still getting the issue.  My code is identical to mschrauth.

**Comment by benschenker** [comment]
@calskin see my point above, you need to use `max` and `min` for it to pass

**Comment by dokkillo** [comment]
@calskin  its fixed, but the patch is not deployed in production :)

**Comment by bigguyjoe1** [comment]
Please unsubscribe me from your mailing list. I no longer wish to receive
emails. Thank you

**Comment by calskin** [comment]
@benschenker @dokkillo I'm sorry.  My brain isn't working properly.

**Comment by BerkeleyTrue** [comment]
@bigguyjoe1 You must unwatch the repo yourself. This isn't a mailing list.

**Comment by bugron** [comment]
Dear camper, your issue is a duplicate and already fixed:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2219
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2218
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2162
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2150
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2008
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1829

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).

**Comment by mohamed-avatarinweb** [comment]
![i did it](https://cloud.githubusercontent.com/assets/15839075/11169376/c1f56978-8bc6-11e5-8278-b80768bc85c4.png)

**Comment by faizaanceg** [comment]
?

**Comment by SaintPeter** [comment]
You have failed to correctly replicate the sample code, excluding the `+ 1` from after `myMin`.

In the future please do not post your code questions all over closed bugs.
1. You can get help and issue confirmation in the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help?utm_source=share-link&utm_medium=link&utm_campaign=share-link)
2. You need to clearly state your issue, not just paste a screenshot and expect us to figure it out.
