### ISSUE TITLE
Missing Bootstrap - Waypoint: Use Responsive Design with Bootstrap Fluid Containers

### ISSUE THREAD

**Issue by jads1073** [FreeCodeCamp/FreeCodeCamp#2467]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-responsive-design-with-bootstrap-fluid-containers has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Had input the appropriate div tags, but still would not go past that lesson. Review instructions and found that the Bootstrap that was supposed to be entered for us was not there, Once I copied and pasted the Bootstrap link then the lesson would let me pass.

"You can add Bootstrap to any app just by including it with <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css"/> at the top of your HTML. But we've gone ahead and automatically added it to your Cat Photo App for you."

**Comment by benschenker** [comment]
Hey @jads1073 thanks for posting!

I haven't been able to reproduce this issue, it looks like bootstrap is in there fine.  I'm going to close this as fixed for now but feel free to reopen if you still experience this issue!

**Comment by michaelcaetano** [comment]
@jads1073 @benschenker Hey, just an FYI that this issue hasn't been resolved. Just experienced same issue with test, had to manually add <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css"/> contrary to the instructions.

**Comment by ahstro** [comment]
Reopening because of @michaelcaetano's comment.

Have you tried a [hard refresh](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Refresh-Your-Browser-Cache)?
I'm suspecting that this isn't, in fact, an issue with FCC, but that the browser might've just failed to fetch the Bootstrap files from their CDN? How are your internet connections? Is this a persistent thing across refreshes, or something that happens once in a while?

**Comment by michaelcaetano** [comment]
@ahstro net connections are good. I didn't consider using a hard refresh or trying to open page in Private Mode on my browser. Thank you for the suggestions, I will keep them in mind for next time. Cheers!

**Comment by ahstro** [comment]
@michaelcaetano Did a refresh solve the problem? If so, this can be closed again.

**Comment by michaelcaetano** [comment]
@ahstro Neither the hard refresh, nor opening the page in Incognito Mode rectified the issue. Still had to manually add the bootstrap link myself.

**Comment by benschenker** [comment]
@michaelcaetano, can you post a screenshot, showing it both with and without the bootstrap link?

**Comment by michaelcaetano** [comment]
@benschenker @ahstro my apologies gentlemen, just got it to work without manually entering the link. Seems it needed more than several refresh attempts.

**Comment by bugron** [comment]
@michaelcaetano feel free to close this issue if your problem is solved, thanks.

**Comment by michaelcaetano** [comment]
Fixed #2467

**Comment by benschenker** [comment]
@michaelcaetano, he means just press the button that says `close` on this github issue. I'll do it for you.

**Comment by hugoender** [comment]
I am experiencing this issue as well. In my opinion, this is still an issue even if a few refreshes get it to work correctly. It should work right off the bat like the rest of the waypoints do without needing special instructions. I recommend reopening this and either fixing it or changing the Waypoint text to tell the camper to include the link to bootstrap themselves.

**Comment by benschenker** [comment]
@hugoender  Usually the refresh just updates the javascript files to the latest ones.  If this helps than it may have been an issue with old code but it is no longer an issue.  If you think the issue still exists, post a screenshot and help us replicate it.  We can only really fix something if it can consistently be replicated for us.

**Comment by hugoender** [comment]
The following image was taken from iOS9 browser but it's the same thing I am seeing on Chrome for Mac and Chrome for Windows. So that's three different systems with three different browsers where the same issue occurs. 

Let me know if you need any additional help replicating this issue. You guys have done a phenomenal job with this site and it would be an honor to help in any way I can. 

![image](https://cloud.githubusercontent.com/assets/6217175/10000017/a4e32616-6067-11e5-8f4a-6aa3ab43d416.png)

**Comment by benschenker** [comment]
Hey @hugoender, I'm having trouble figuring out what I am supposed to see in your screenshot? Should we chat in gitter and try to resolve this there?

**Comment by hugoender** [comment]
@benschenker Yes, let's chat on gitter. When would you be available? I can get on tonight (24th) after 6:30pm. Any specific room?

I have been in the help room these past couple of days helping people out with their problems and I have already run into two other campers that have seen this exact issue and gone into the help room asking why.

**Comment by benschenker** [comment]
Just message me in a private message, I'll try to respond tonight

**Comment by benschenker** [comment]
Ah yes I finally understand!  The complaint is that the wording of the challenge says 

```
You can add Bootstrap to any app just by including it with 
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css"/> 
at the top of your HTML. 
```
But then it says:
```
But we've gone ahead and automatically added it to your Cat Photo App for you.
```
Which suggests that it should be physically prepended to the editor when in reality it is just loaded in the background.

We should update the description to say something like:
```
But we've added it for you to this page behind the scenes.
```

**Comment by JimC86** [comment]
that rewording helped me a little, but im still having issues with this as well, im sure its just me doing something wrong though and not an actual issue with the lesson... I know how to add the class to my div tag but I don't get the nesting part (I think that's whats messing up) If anyone can just post what it should look like, or be more specific about what to type since this lesson has had issues that would be helpful.. Ill go through 20 lessons no problem, then get to one where its just a little quirk they I didn't understand exactly what they were wanting me to do.  So far I've found the most challenging part just figuring out the actual instructions (for the most part, however I am obviously still pretty early on)

**Comment by samfisher6** [comment]
@JimC86 have you figured this one out already, i'm having trouble with what it's asking me to do.

**Comment by SeoulMan** [comment]
I am stuck here too. I can't understand the instruction.

**Comment by JimC86** [comment]
I'm sorry I don't have Internet atm, but I can help you when I do  Google
that lesson name with solution and click like 2 or 3 links down... I
believe you just add a <div> then put the <\div> in the right place. Good
luck

**Comment by samfisher6** [comment]
Sorry for the late response but I figured it out. place a <div> at the beginning of all your h2 and a <\div> at the end

**Comment by SeoulMan** [comment]
got it! thank you.

**Comment by vanellelove** [comment]
Make sure you have nested all HTML elements in .container-fluid.

**Comment by trondweiseth** [comment]
Make sure you have nested all HTML elements in .container-fluid

**Comment by MD-J** [comment]
no solution?

**Comment by ajsmithsjc** [comment]
How do you nest all HTML elements in .container-fluid????

**Comment by MD-J** [comment]
<div class="container-fluid">
HTML elements 
</div>

**Comment by MD-J** [comment]
<div class="container-fluid">


HTML

</div>

**Comment by MD-J** [comment]
Argh

**Comment by MD-J** [comment]
<div class="container-fluid ">
</div>

**Comment by MD-J** [comment]
Div class="container-fluid "
Open and close

**Comment by MelissaLoggins** [comment]
I had the same problem. When I copied and pasted the link to add Bootstrap at the top, my lesson went through just fine.

**Comment by cappi74** [comment]
November 18th, 2016 checking in... Same issue, had to paste the url in. Using the latest version of Chrome and have pretty fast internet.

**Comment by shruti1305** [comment]
i am actually unable to understand what to do in this.the .container-fluid ,where should i place it?please help me
