### ISSUE TITLE
Run code button in challenge not working

### ISSUE THREAD

**Issue by elyak123** [FreeCodeCamp/FreeCodeCamp#2690]
Challenge http://www.freecodecamp.com/challenges/waypoint-comment-your-javascript-code has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

In this challenge the run code button doesn't work.

**Comment by BerkeleyTrue** [comment]
This should be fixed now. Can you give it a try?

**Comment by cusxio** [comment]
It's not really fixed. I had to click it multiple times. It actually not only for that challenge. I've experienced it sometimes on multiple challenges.

**Comment by benmcmahon100** [comment]
@cusxio Everytime you click it you restart the execution of the code. The testing isn't instant which is what is causing the button to be slow

**Comment by cusxio** [comment]
@benmcmahon100 is it by design that I have to click Run Code twice ? First time for the test to evaluate, and 2nd time for the "Next Challenge Button" to appear?

**Comment by BerkeleyTrue** [comment]
@cusxio You don't need to click the button twice. You just need to wait for execution to complete.

**Comment by elyak123** [comment]
I understand that the testing might not be instant, however it does need to be clicked two times to pass to the next challenge.

**Comment by denmch** [comment]
I can confirm that Run needs to be clicked twice in both the latest stable releases of Chrome and Firefox on Mac. After resetting the code and doing a hard reset, this is indeed the case. Once you've passed the first time with two clicks (one click to pass the tests and another click to summon the modal and advance), you can pass again with just one click.

**Comment by joshcronkhite** [comment]
I also waited quite a bit of time with no activity. Clicking on it a second time resolves. I'm using Chrome on MacOS X 10.10.5.

**Comment by BerkeleyTrue** [comment]
This is a confirmed issue which we will track here #2772

Happy Coding!

**Comment by sarthi92** [comment]
on http://www.freecodecamp.com/challenges/say-hello-to-html-elements and nearly every challenge i try, Run tests button is not working. Furthermore, the mobile image is empty, and is not updated with code. Please help.

**Comment by benmcmahon100** [comment]
@sarthi92 disable any browser extensions. Also which browser are you using

**Comment by sarthi92** [comment]
@benmcmahon100 thank you, everything's working fine now. I am using Chrome.

**Comment by emorres25** [comment]
The Run tests button does not work for me at all.
I disabled all the extensions, and tried double clicking. Still doesn't work.

**Comment by benmcmahon100** [comment]
@emorres25 What browser are you using and what errors are in the browser console?

**Comment by sarthi92** [comment]
@benmcmahon100 Yes, Run tests button is not working. It worked for a while yesterday, but isn't working now. I disabled all the extensions. I use Chrome.

**Comment by sarthi92** [comment]
Refused to connect to 'http://203.94.243.63:3000/nadip/?json=%7B%22url%22%3A%22%2Fbower%5Fcomponen…amp%2Ecom%22%2C%22categories%22%3A%5B1%5D%2C%22reputations%22%3A%5B1%5D%7D' because it violates the following Content Security Policy directive: "connect-src vimeo.com 'self'".

commonFramework-88b9c90a72.js:1 Object {readyState: 0, responseText: undefined, status: 0, statusText: "error"}n.fromCallback.delay.flatMap.subscribe.n @ commonFramework-88b9c90a72.js:1Qa.AnonymousObserver.b.next @ vendor-main-c4d40c8dec.js:52Qa.internals.AbstractObserver.b.onNext @ vendor-main-c4d40c8dec.js:51(anonymous function) @ vendor-main-c4d40c8dec.js:51c.next @ vendor-main-c4d40c8dec.js:55Qa.internals.AbstractObserver.b.onNext @ vendor-main-c4d40c8dec.js:51(anonymous function) @ vendor-main-c4d40c8dec.js:51c.next @ vendor-main-c4d40c8dec.js:55Qa.internals.AbstractObserver.b.onNext @ vendor-main-c4d40c8dec.js:51c @ vendor-main-c4d40c8dec.js:52b.subscribeCore @ vendor-main-c4d40c8dec.js:52(anonymous function) @ vendor-main-c4d40c8dec.js:51c @ vendor-main-c4d40c8dec.js:52Qa.ObservableBase.d._subscribe @ vendor-main-c4d40c8dec.js:52(anonymous function) @ vendor-main-c4d40c8dec.js:52Qa.Observable.Mc.subscribe.Mc.forEach @ vendor-main-c4d40c8dec.js:52b.error @ vendor-main-c4d40c8dec.js:52Qa.internals.AbstractObserver.b.onError @ vendor-main-c4d40c8dec.js:52c.onError @ vendor-main-c4d40c8dec.js:52(anonymous function) @ vendor-main-c4d40c8dec.js:51c.error @ vendor-main-c4d40c8dec.js:55Qa.internals.AbstractObserver.b.onError @ vendor-main-c4d40c8dec.js:52c.error @ vendor-main-c4d40c8dec.js:52Qa.internals.AbstractObserver.b.onError @ vendor-main-c4d40c8dec.js:52c.onError @ vendor-main-c4d40c8dec.js:52(anonymous function) @ vendor-main-c4d40c8dec.js:51c.error @ vendor-main-c4d40c8dec.js:55Qa.internals.AbstractObserver.b.onError @ vendor-main-c4d40c8dec.js:52b.error @ vendor-main-c4d40c8dec.js:52Qa.internals.AbstractObserver.b.onError @ vendor-main-c4d40c8dec.js:52c.onError @ vendor-main-c4d40c8dec.js:52(anonymous function) @ vendor-main-c4d40c8dec.js:51c.error @ vendor-main-c4d40c8dec.js:55Qa.internals.AbstractObserver.b.onError @ vendor-main-c4d40c8dec.js:52Qa.FlatMapObservable.c.error @ vendor-main-c4d40c8dec.js:52Qa.internals.AbstractObserver.b.onError @ vendor-main-c4d40c8dec.js:52c.onError @ vendor-main-c4d40c8dec.js:52(anonymous function) @ vendor-main-c4d40c8dec.js:51c.error @ vendor-main-c4d40c8dec.js:55Qa.internals.AbstractObserver.b.onError @ vendor-main-c4d40c8dec.js:52c.error @ vendor-main-c4d40c8dec.js:52Qa.internals.AbstractObserver.b.onError @ vendor-main-c4d40c8dec.js:52c.onError @ vendor-main-c4d40c8dec.js:52(anonymous function) @ vendor-main-c4d40c8dec.js:51c.error @ vendor-main-c4d40c8dec.js:55Qa.internals.AbstractObserver.b.onError @ vendor-main-c4d40c8dec.js:52d.error @ vendor-main-c4d40c8dec.js:53Qa.internals.AbstractObserver.b.onError @ vendor-main-c4d40c8dec.js:52c.onError @ vendor-main-c4d40c8dec.js:52(anonymous function) @ vendor-main-c4d40c8dec.js:51c.error @ vendor-main-c4d40c8dec.js:55Qa.internals.AbstractObserver.b.onError @ vendor-main-c4d40c8dec.js:52b.error @ vendor-main-c4d40c8dec.js:52Qa.internals.AbstractObserver.b.onError @ vendor-main-c4d40c8dec.js:52c.onError @ vendor-main-c4d40c8dec.js:52(anonymous function) @ vendor-main-c4d40c8dec.js:51c.error @ vendor-main-c4d40c8dec.js:55Qa.internals.AbstractObserver.b.onError @ vendor-main-c4d40c8dec.js:52Qa.FlatMapObservable.c.error @ vendor-main-c4d40c8dec.js:52Qa.internals.AbstractObserver.b.onError @ vendor-main-c4d40c8dec.js:52c.onError @ vendor-main-c4d40c8dec.js:52(anonymous function) @ vendor-main-c4d40c8dec.js:51c.error @ vendor-main-c4d40c8dec.js:55Qa.internals.AbstractObserver.b.onError @ vendor-main-c4d40c8dec.js:52c.error @ vendor-main-c4d40c8dec.js:53Qa.internals.AbstractObserver.b.onError @ vendor-main-c4d40c8dec.js:52c.onError @ vendor-main-c4d40c8dec.js:52(anonymous function) @ vendor-main-c4d40c8dec.js:51c.error @ vendor-main-c4d40c8dec.js:55Qa.internals.AbstractObserver.b.onError @ vendor-main-c4d40c8dec.js:52b.error @ vendor-main-c4d40c8dec.js:52Qa.internals.AbstractObserver.b.onError @ vendor-main-c4d40c8dec.js:52c.onError @ vendor-main-c4d40c8dec.js:52(anonymous function) @ vendor-main-c4d40c8dec.js:51c.error @ vendor-main-c4d40c8dec.js:55Qa.internals.AbstractObserver.b.onError @ vendor-main-c4d40c8dec.js:52c.onError @ vendor-main-c4d40c8dec.js:52c.onError @ vendor-main-c4d40c8dec.js:52(anonymous function) @ vendor-main-c4d40c8dec.js:52(anonymous function) @ vendor-main-c4d40c8dec.js:51g @ vendor-main-c4d40c8dec.js:52b @ vendor-main-c4d40c8dec.js:51mc.invokeCore @ vendor-main-c4d40c8dec.js:51mc.invoke @ vendor-main-c4d40c8dec.js:51b @ vendor-main-c4d40c8dec.js:51(anonymous function) @ vendor-main-c4d40c8dec.js:51c.schedule @ vendor-main-c4d40c8dec.js:51a.scheduleRecursive @ vendor-main-c4d40c8dec.js:51Qa.internals.ScheduledObserver.b.ensureActive @ vendor-main-c4d40c8dec.js:52Qa.ReplaySubject.Xb.onError @ vendor-main-c4d40c8dec.js:55c.onError @ vendor-main-c4d40c8dec.js:52(anonymous function) @ vendor-main-c4d40c8dec.js:51c.error @ vendor-main-c4d40c8dec.js:55Qa.internals.AbstractObserver.b.onError @ vendor-main-c4d40c8dec.js:52c.onError @ vendor-main-c4d40c8dec.js:52(anonymous function) @ vendor-main-c4d40c8dec.js:51c.error @ vendor-main-c4d40c8dec.js:55Qa.internals.AbstractObserver.b.onError @ vendor-main-c4d40c8dec.js:52(anonymous function) @ commonFramework-88b9c90a72.js:1j @ vendor-main-c4d40c8dec.js:2k.fireWith @ vendor-main-c4d40c8dec.js:2x @ vendor-main-c4d40c8dec.js:4(anonymous function) @ vendor-main-c4d40c8dec.js:4
vendor-main-c4d40c8dec.js:51Uncaught #<Object>e @ vendor-main-c4d40c8dec.js:51c.error @ vendor-main-c4d40c8dec.js:55Qa.internals.AbstractObserver.b.onError @ vendor-main-c4d40c8dec.js:52(anonymous function) @ commonFramework-88b9c90a72.js:1j @ vendor-main-c4d40c8dec.js:2k.fireWith @ vendor-main-c4d40c8dec.js:2x @ vendor-main-c4d40c8dec.js:4(anonymous function) @ vendor-main-c4d40c8dec.js:4

**Comment by SaintPeter** [comment]
@sarthi92 Some ISPs (especially Indian ISPs) are known to intercept their user's connections to inject ads and do caching.  This breaks the FCC site.  You can get around this by [Using browsec for securing your connection to fcc](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Using-browsec-for-securing-your-connection-to-fcc).  

Give that a try and see if it clears up the issue.

**Comment by benmcmahon100** [comment]
This issue is being locked. If you are experiencing an issue with the run button. Please look for a more current issue or open your own
