### ISSUE TITLE
Page won't stop refreshing

### ISSUE THREAD

**Issue by eyeMNaughtReal** [FreeCodeCamp/FreeCodeCamp#2709]
Challenge http://www.freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

There is like an endless refresh on this, for me.

**Comment by BerkeleyTrue** [comment]
When you navigate to the page it just constantly refreshes?

**Comment by eyeMNaughtReal** [comment]
At first it did, but after about 30 seconds it would stop. This issue continued with the rest of the slot machine JS portion.

**Comment by BerkeleyTrue** [comment]
What browser are you using?

**Comment by eyeMNaughtReal** [comment]
Chrome.  I don't know what version, I'm already away from my computer.

**Comment by LuckyOreo** [comment]
I've noticed this happen in the SlotMachine challenges when the I am not signed in and I load the slotMachine challenge page from the map page.  I use the back and forward buttons to go back and forth from the map page back to the challenge page, then it starts to continually refresh the page until it times out.

**Comment by BerkeleyTrue** [comment]
@eyeMNaughtReal and @LuckyOreo I've deployed some changes that hopefully fixes this.

Do a hard refresh and let me know if you run into it again.

**Comment by BerkeleyTrue** [comment]
I think I might have just run into it. Seems like what is actually happening is the web worker is continuously being called. 

cc @benmcmahon100 

![waypoint__target_the_parent_of_an_element_using_jquery___free_code_camp](https://cloud.githubusercontent.com/assets/6775919/9487507/0e4bb6e0-4b87-11e5-9861-d71d72792520.png)

**Comment by BVegan** [comment]
I'm still having the same problem. The cellphone display flashes it's content. The page continues to refresh. And the popup continues to popup telling me to go to next challenge

**Comment by BerkeleyTrue** [comment]
This should be fixed now. Please re-open if this issue still persists. Happy Coding!
