### ISSUE TITLE
Code is correct but continues to fail 

### ISSUE THREAD

**Issue by elattanzio** [FreeCodeCamp/FreeCodeCamp#2759]
Challenge http://www.freecodecamp.com/challenges/waypoint-make-images-mobile-responsive has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

My code is correct according to the challenge, but this piece still is marked as undone:
Add a second image with the src of http://bit.ly/fcc-running-cats.

Screenshot is attached.
<img width="1049" alt="screen shot 2015-08-26 at 10 12 06 pm" src="https://cloud.githubusercontent.com/assets/7574806/9510999/ab1e9cd6-4c3f-11e5-9476-a4b2381cfbbe.png">

**Comment by denmch** [comment]
I duplicate this, but after hard refresh in Chrome (Cmd+Shift+R on Mac, or Ctrl+Shift+R on a Windows machine), all tests showed as passed.

This was true for another reported bug, as well, and each page required a separate refresh, so I suspect this may be the solution for other apparent bugs as well..

**Comment by benschenker** [comment]
Looks like this has been fixed. Thanks!

**Comment by metasean** [comment]
I'm running into the exact some problem.  At this point I've done "reset", browser page refresh, and browser page shift-refresh, individually and in combination, but it's still failing the third test.

code:
```
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<div class="container-fluid">
  <h2 class="red-text">CatPhotoApp</h2>

  <p>Click here for <a href="#">cat photos</a>.</p>

  <a href="#"><img class="smaller-image thick-green-border img-responsive" src="http://bit.ly/fcc-relaxing-cat"></a>
  <img class="img-responsive" src="http://bit.ly/fcc-running-cats">

  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</div>
```
failing test:
`Add a second image with the src of http://bit.ly/fcc-running-cats`

**Comment by bigkatspence** [comment]
I have already sent in a bug report ended up skipping over it

**Comment by bigkatspence** [comment]
It is a bug issue just skip over
On Sep 30, 2015 12:13 PM, "MetaSean" <notifications@github.com> wrote:
>
> I'm running into the exact some problem. At this point I've done "reset",
browser page refresh, and browser page shift-refresh, individually and in
combination, but it's still failing the third test.
>
> code:
>
> <link href="http://fonts.googleapis.com/css?family=Lobster"
rel="stylesheet" type="text/css">
> <style>
>   .red-text {
>     color: red;
>   }
>
>   h2 {
>     font-family: Lobster, Monospace;
>   }
>
>   p {
>     font-size: 16px;
>     font-family: Monospace;
>   }
>
>   .thick-green-border {
>     border-color: green;
>     border-width: 10px;
>     border-style: solid;
>     border-radius: 50%;
>   }
>
>   .smaller-image {
>     width: 100px;
>   }
> </style>
>
> <div class="container-fluid">
>   <h2 class="red-text">CatPhotoApp</h2>
>
>   <p>Click here for <a href="#">cat photos</a>.</p>
>
>   <a href="#"><img class="smaller-image thick-green-border
img-responsive" src="http://bit.ly/fcc-relaxing-cat"></a>
