### ISSUE TITLE
Small Typo Error

### ISSUE THREAD

**Issue by shaikhatik0786** [FreeCodeCamp/FreeCodeCamp#2812]
Challenge http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

You missed the bracket ")" in the description guys

![screenshot_1](https://cloud.githubusercontent.com/assets/4403762/9552851/a7c654da-4dd8-11e5-8110-3a89fbb52957.png)

**Comment by bugron** [comment]
@shaikhatik0786 thanks for posting this issue!
Actually everything is fine and this issue is already solved. See [my previous comment](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2773#issuecomment-135506542).

Proof (5 minutes old screenshot, which is done in FF Incognito window).
![](http://i.imgur.com/fUj4p1J.png)
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by shaikhatik0786** [comment]
@bugron well, it still shows for me. And I cleared the cache before this

**Comment by bugron** [comment]
Interesting. @shaikhatik0786 try in incognito mode. Anyway, problem is 100% solved ([see](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/jquery.json#L19) source code, lines 19 and 20)

**Comment by benschenker** [comment]
Closing this as stale, please reopen if the issue persists
