### ISSUE TITLE
Prioritize One Style Over Another- problem 

### ISSUE THREAD

**Issue by meening42** [FreeCodeCamp/FreeCodeCamp#2822]
Challenge http://www.freecodecamp.com/challenges/waypoint-prioritize-one-style-over-another has an issue.

I realy can't see what i'm doing wrong. Can someone please help?

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  pink-text{
    color: pink;
  }
</style>

<h1 style="pink-text">Hello World!</h1>

**Comment by meening42** [comment]
Text should have been pink and not green

**Comment by meening42** [comment]
Found the error. I have no dot infront of the pink-text

**Comment by bugron** [comment]
@meening42 thanks for posting this issue!
@BerkeleyTrue seems this issue is solved and can be closed, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by Fagro** [comment]
Ok, maybe I'm doing something wrong but the issue is still there.

![shouldbepink](https://cloud.githubusercontent.com/assets/1713133/9704693/8d24519e-547d-11e5-9a4f-b6c64c0eb68e.PNG)

## Applying the same style to another exercises webpage and it works:

![pink](https://cloud.githubusercontent.com/assets/1713133/9704709/0d31ebc6-547e-11e5-99e4-4a0008060576.PNG)

**Comment by bugron** [comment]
@Fagro thanks for posting this issue!
Remove the colon after **.pink-text**.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by Fagro** [comment]
Thank bugron.

**Comment by lmack82** [comment]
Here's one... 
![screen](https://cloud.githubusercontent.com/assets/17714490/13628748/9565fa18-e589-11e5-8439-6a5a1af433a5.png)

The display actually shows it working, yet somehow the assignment isn't counting this as correct.

According to the test indicator, I have...

```
Your h1 element should have the class pink-text.: passed
Your <style> should have a pink-text CSS class with its color set to pink.: failed
Your h1 element should be pink.: passed
```

**Comment by Waqas70011** [comment]
I checked my code twice and it is correct but the question just shows this is my code: <style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text 
    Color: pink;
  }
</style>
<h1 class="pink-text">Hello World!</h1>

**Comment by yahyax5** [comment]
It should be like this...
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: pink;
    .pink-text{
      color:pink;
    }
  }
</style>
<h1 class="pink-text"> Hello World!</h1>

**Comment by vladas1987** [comment]
<style>
 body { background-color: black; 
   font-family: Monospace; 
  
  }
   .pink-text
  {
  color:pink; 
  } 
</style>
<h1 class="pink-text"> Hello World!</h1>

**Comment by vladas1987** [comment]
<style>
 body { background-color: black; 
   font-family: Monospace; 
  
  }
   .pink-text
  {
  color:pink; 
  } 
</style>
<h1 class="pink-text"> Hello World!</h1>

**Comment by texas2010** [comment]
@vladas1987 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by Romiom** [comment]
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color :green;
   }
  pink-text {
  color: pink;
  }
 </style>
<h1 class="pink-text">Hello World!</h1>
