### ISSUE TITLE
Missing Instructions

### ISSUE THREAD

**Issue by JesseNoBata** [FreeCodeCamp/FreeCodeCamp#2984]
Challenge http://freecodecamp.com/challenges/waypoint-make-instances-of-objects-with-a-constructor-function has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The challenge only gives information and then in the assertions pane, only clue is that:

"The property engine of myCar should be a number"

--There should probably be some wording what the challenge is looking for.

**Comment by bugron** [comment]
@JesseNoBata thanks for pointing this out!

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by jarrodmac100** [comment]
I had the same issue.  It says put a property of engine but it wants engines (plural) instead.
so      myCar.engines=1

**Comment by Luomint** [comment]
Definitely missing an instruction, we were never shown how to add a new property to an instance.
instance.property = "something";
Like myCar.engines=1;

**Comment by flossless** [comment]
I agree with Luomint and others, I'm really struggling to understand what is being asked. There seems to be a real lack of instruction and back story as to why or how to do the things we are supposed to be doing.

I feel like I need to read a companion book on programming and the different terms in order just to understand what's going on. I think this might be a sticking point for a lot of folks new to programming who might end up quitting in frustration.

**Comment by bugron** [comment]
Reopening this issue. Thanks to all for your feedback. Seems I misunderstood what is this issue about that time.

**Comment by flossless** [comment]
Happy to help. I like the program and want it to be a success.

And I want to be successful at it too :)

**Comment by blairdow** [comment]
I was having the same issue... You basically have to guess what the syntax is. Also re: what flossless was saying about a lack of explanation and reasons behind what we are doing, I agree. I may go back to codecademy, I felt like I was learning more from the way their program is set up.

**Comment by bschaden** [comment]
I agree with flossless. The whole object oriented section so far is very poorly explained. I need to look up everything somewhere else, there is no explanation of syntax and terms and what is really going on.  I'm really just guessing and (barely)passing the challenges by mechanically typing something in but not understanding why.

**Comment by AmyMcKnight** [comment]
Just wanted to add that I ran into this and am struggling as well. I went over the lessons that came before several times to see if I had missed something. Glad to know that I wasn't missing something but looking forward to this section being fixed :-)

**Comment by blairdow** [comment]
It sucks! I've actually gone back to codecademy for now because I learn
more from the way their lessons are structured.

____________

*whenwhitegirlslovehiphop.tumblr.com
<http://whenwhitegirlslovehiphop.tumblr.com>blairdow@gmail.com
<blairdow@gmail.com>*
*707.337.8033*
*meow*

**Comment by benmcmahon100** [comment]
This was fixed a while ago but has only gotten pushed recently to the site, If you guys have any more feedback please feel free to open a new issue or reopen this one!

**Comment by easmsm** [comment]
I still don't see this as being fixed. This seems to be a common issue with freecodecamp - there's no example - no reference - and the only help is the chat. I don't want to have it "fixed" like code academy, I just need to have some sort of frame of reference.

**Comment by aguaca** [comment]
no explanation, no guideline, nothing...there should be a better way to coding

**Comment by blairdow** [comment]
Yah... codecademy is much better now IMO

____________

*whenwhitegirlslovehiphop.tumblr.com
<http://whenwhitegirlslovehiphop.tumblr.com>blairdow@gmail.com
<blairdow@gmail.com>*
*707.337.8033*
*meow*

**Comment by ltegman** [comment]
Working on some updates to these lessons right now. Hoping to have them up soon.

**Comment by gitasong** [comment]
I'm having the same problem as others on this thread. No explanation anywhere of the syntax needed for making a property within an instance, e.g.: myCar.engines = 1. This needs to be explained. @ltegman : How are the updates coming?

**Comment by MataOg** [comment]
I have the same problem

**Comment by SaintPeter** [comment]
@MataOg Can you please give more details on the source of your confusion?  @ltegman recently rewrote these waypoints and they should be significantly more descriptive.  I just confirmed that they are live.

**Comment by MataOg** [comment]
It is ok, I was litle confused but I got it now.
Thanks.
