### ISSUE TITLE
Seed data bug in ux-improvements for start-a-node.js-server challenge

### ISSUE THREAD

**Issue by ChillTrain** [FreeCodeCamp/freecodecamp#324]
In the ux-improvements branch:

~~Looks like the /challenges/start-a-node.js-server route is going to the MongoDB challenge instead of whetever node challenge it should be going to.~~

Looks like this is an issue with the seed data here:

https://github.com/FreeCodeCamp/freecodecamp/blob/ux-improvements/seed_data/coursewares.json#L517-528

**Comment by QuincyLarson** [comment]
Thanks! I've fixed the copy for all of these waypoints.

**Comment by ChillTrain** [comment]
No problem.  You may already know this, but it's still showing the Mongo video...
