### ISSUE TITLE
Array.sort()'s callback performs different between browsers

### ISSUE THREAD

**Issue by ozgunbal** [freeCodeCamp/freeCodeCamp#34543]
**Describe your problem and how to reproduce it:**
Example `reverseAlpha` function at the left behaves different in Google Chrome and Firefox. Chrome doesn't sort  but Firefox does.

Below implementation works at both browsers:
```js
function reverseAlpha(arr) {
  return arr.sort(function(a, b) {
    return a < b ? 1 : -1;
  });
}
reverseAlpha(['l', 'h', 'z', 'b', 's']);
```

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/functional-programming/sort-an-array-alphabetically-using-the-sort-method/

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 70.0
* Operating System: Ubuntu 18.04 LTS

_and_

* Browser Name: Mozilla Firefox
* Browser Version: 63.0
* Operating System: Ubuntu 18.04 LTS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![array_sort](https://user-images.githubusercontent.com/16080180/49510647-ef1add00-f899-11e8-9c7f-de132a20797f.png)

**Comment by ezioda004** [comment]
Hi @ozgunbal,

Thank you for opening this issue. The issue has been fixed in https://github.com/freeCodeCamp/freeCodeCamp/pull/25978. It'll be shipped soon.

**Comment by drecali** [comment]
Hi @ezioda004 , 
PR #25978 only added Chrome-friendly sample code for the reverse alphabetical sort. The normal alphabetical sort sample still doesn't work in Chrome, but does in Firefox.

Also, the live FCC challenge page is outdated compared to the GitHub version. Do the GitHub changes get pushed to the live site on a schedule, or do they need to be manually pushed? 

> Hi @ozgunbal,
> 
> Thank you for opening this issue. The issue has been fixed in #25978. It'll be shipped soon.

**Comment by ezioda004** [comment]
Hi @drecali,
Could you elaborate more on this with example/screenshots?
>The normal alphabetical sort sample still doesn't work in Chrome, but does in Firefox.

>Do the GitHub changes get pushed to the live site on a schedule, or do they need to be manually pushed?

There is no defined schedule, the master branch is pushed to production when the core team thinks it should be pushed. The new production build will be shipped soon.

**Comment by drecali** [comment]
Hi @ezioda004 

Here are screenshots and tables below summarizing the issue. In short, the sample code for ascending sort is an example of how to sort numbers. It works for numbers but does not work when applied to letters/strings in Chrome 70+. The sample code for the reverse alphabetical sort also doesn't work in Chrome 70+ but does in FireFox. I think it would be best to have sample code that applies to the challenge, and works across major browsers.

### FCC Live Site:
![Free Code Camp Screenshot](https://i.imgur.com/6chAVSk.jpg)

### GitHub version:
![GitHub version](https://i.imgur.com/vZInCSs.jpg)

### FCC Live Site:
| Sort Type   |      Sample Code      |  Chrome 70+ | FireFox |
|----------|:-------------:|:------:|:-------:|
| Alphabetical |  `return a - b;` | __FAIL__ | PASS
| Reverse-Alpha |  `return a < b;` |   __FAIL__ | PASS

### GitHub Version:
| Sort Type   |      Sample Code      |  Chrome 70+ | FireFox |
|----------|:-------------:|:------:|:-------:|
| Alphabetical |  `return a - b;` | __FAIL__ | PASS
| Reverse-Alpha |  `return a === b ? 0 : a < b ? 1 : -1;` __*__ |   PASS | PASS

*Note: there is a typo in the second sample code block of the GitHub version. I submitted PR #34716 to fix it.

Hope this info helps. Please let me know if anything is unclear.

Thanks for explaining about the production build!

**Comment by ezioda004** [comment]
@drecali Thanks for the detail write up. 

The `reverseAlpha` as you can see has been fixed in the master and will be live soon. The alphabetical sort is what the user is suppose to write so its not an issue.
Now, about `ascendingOrder` its a working example for numbers and not strings so IMO this is fine too.

**Comment by drecali** [comment]
Thanks @ezioda004
