### ISSUE TITLE
Client crashes with React component recursive renders

### ISSUE THREAD

**Issue by jagzmz** [freeCodeCamp/freeCodeCamp#36118]
**Describe the bug**
Whenever a class component renders itself crashes the website

**To Reproduce**
1. Go to '[Default Props Challenge](https://learn.freecodecamp.org/front-end-libraries/react/override-default-props/)'
2. Type `<ShoppingCart />` instead of `<Items />`

**Expected behavior**
Should throw an error or should not render invalid code

**Screenshots**
![](https://i.imgur.com/hxoC2dr.png)
**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Browser: Chrome
 - Version: 73.0.3683.75

**Additional context**
This issue is for most of challenges

**Comment by RandellDawson** [comment]
It is like a recursive function that has no end condition.  It just attempts to keep rendering itself which keeps rendering itself and so on.

**Comment by jagzmz** [comment]
> It is like a recursive function that has no end condition. It just attempts to keep rendering itself which keeps rendering itself and so on.

Yea, it keeps rendering itself.

**Comment by yj7o5** [comment]
I would be more than happy to take a look at this :) Will be my first OSS PR

**Comment by yj7o5** [comment]
hmm now that I take a more close look at this ... the problem is with the logic itself and this would be the expected behavior since you're running into a never ending program or sort of a forever loop due to this recursion. But It maybe nice to detect such a case like this and guide the user or maybe provide hints so as to a) not cause the browser to crash and b) enable the user in finding the root cause of the problem in order to server better UX. 

And upon bit more researching it seems like FCC already has this protection in placed but for loops (infinte loop)[https://www.freecodecamp.org/forum/t/free-code-camp-infinite-loop-protection/19550], 

Maybe @RandellDawson we could wrap the code/program around `try catch` and if we encounter a 'Maximum call stack size exceeded' we display an alert of some sort, we can get from the stack the exact line that caused the issue. Thoughts?

**Comment by yj7o5** [comment]
so kinda like how KhanAcademy(as I remember once playing around) does it in their editors but we can use this as an inspiration:-
![image](https://user-images.githubusercontent.com/7938533/58388166-b1914400-7fe0-11e9-818d-d04b13a83daf.png)

This may help a lot the users (especially beginners) while at the same time provide a link to what this error potentially means.

Let me know of what y'all think and I'll try to come up with the implementation.

**Comment by RandellDawson** [comment]
@ValeraS Any thoughts?

**Comment by ojeytonwilliams** [comment]
@yj7o5 Codepen works that way, too - I found out when I tried to recreate this!  

The odd thing is that generic build errors (i.e. syntax errors) get caught and logged just fine, so I think the error handling is set up okay.  It seems this isn't throwing an error.

**Comment by yj7o5** [comment]
@ojeytonwilliams so codepen doesn't crash and does shows an error but in the console which means one would have no clue until s/he opens up the console. Not the end of the world, but still it'd be nice to give the user an indication on the editor itself in an effort of providing better UX/learning experience.

**Comment by ojeytonwilliams** [comment]
Agreed. It should report the error below the editor and to the console. Same as other build errors.

**Comment by ValeraS** [comment]
Codepen crashes with a code from a topic as well. They prevent only infinite loops, the same way as we do. Each loop in the program receives a time limit.

On freecodecamp.org, simple recursion throws `Maximum call stack size exceeded` error without a crash as well.
![image](https://user-images.githubusercontent.com/10867286/58941302-23595280-8784-11e9-8cf9-57f19ba3637b.png)

KhanAcademy does not have React lessons, so cannot be tested. But KhanAcademy uses another approach to preventing infinite execution: for each loop and function execution, they check the time from start and if it exceeded a limit, break the program execution.

**Comment by krishnadevz** [comment]
**In 2020 this 🔽 issue is coming please see and fix it ASAP**
```
const TypesOfFruit = () => {
  return (
    <div>
      <h2>Fruits:</h2>
      <ul>
        <li>Apples</li>
        <li>Blueberries</li>
        <li>Strawberries</li>
        <li>Bananas</li>
      </ul>
    </div>
  );
};

const Fruits = () => {
  return (
    <div>
      { /* change code below this line */ }
<Fruits/>
      { /* change code above this line */ }
    </div>
  );
};

class TypesOfFood extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <div>
        <h1>Types of Food:</h1>
        { /* change code below this line */ }

        { /* change code above this line */ }
      </div>
    );
  }
};

```
With this thing one challenge is ✔ but when i type **<TypesOfFood/>** After returning component  everything is freezed/browserToo now i cleared the issue to much extent i think only problem is with **<TypesOfFood/>** it is going in infinite loop hope this helps now  and problem is fixed ASAP

**Comment by krishnadevz** [comment]
**issue is solved now i called that component incorrectly everyone can use the below code and see the difference and working  **
```
const TypesOfFruit = () => {
  return (
    <div>
      <h2>Fruits:</h2>
      <ul>
        <li>Apples</li>
        <li>Blueberries</li>
        <li>Strawberries</li>
        <li>Bananas</li>
      </ul>
    </div>
  );
};

const Fruits = () => {
  return (
    <div>
      { /* change code below this line */ }
<TypesOfFruit/>
      { /* change code above this line */ }
    </div>
  );
};

class TypesOfFood extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <div>
        <h1>Types of Food:</h1>
        { /* change code below this line */ }
<Fruits/>
        { /* change code above this line */ }
      </div>
    );
  }
};

```

**Comment by danielgarm** [comment]
The issue is still present as of April 2020. It is reproducible in any browser and operating system as well.

**Comment by Sky020** [comment]
@ojeytonwilliams , Do we have any functions to test for recursion? Or, are we going to move ahead with this issue, and create a test looking for a component called within itself?

**Comment by ojeytonwilliams** [comment]
@Sky020 no, the only thing we specifically protect against is infinite `for` or `while` loops.  Recursion is a bit harder to deal with.  For pure JavaScript it's okay, as Valeriy mentioned above

```js
function a() {
  b();
}

function b() {
  a();
}

a();
```
throws an error, but does not crash the browser.  That's not the case for React and I don't know enough about the internals of React to say why that is.  Possibly the browser runs out of memory before the stack limit is hit.

> create a test looking for a component called within itself

Do you mean something like this? Add a step that checks the code for functions like:

```jsx
const Fruits = () => {
  return (
   <Fruits/>
  );
};
```

and the analogous class structures before rendering?  I think that's a reasonable idea.  If most people are making this kind of mistake, it should reduce the frustration a bit.

@moT01 what do you reckon?

**Comment by Sky020** [comment]
@ojeytonwilliams , I think the reason is React components are stored in a virtualDOM made up of their children. So, a component rendered within itself causes an infinitely deep object.
>Do you mean something like this?

Yes, that exactly.

**Comment by moT01** [comment]
Sounds good to me. Yea, I'm not sure how that test would be written. But I did a quick forum search and found enough issues of this happening that I think it would be worth looking into finding a solution. I gave codepen a quick test and their site just runs the infinite rendering as well. I did find [this article](https://www.bitovi.com/blog/recursive-react-components) which points out a case where recursive rendering is useful (just skimmed through it).

What about some kind of timeout on the rendering of the preview?

**Comment by ojeytonwilliams** [comment]
Thanks for sharing that, I hadn't realised you might want to use recursive components.

In that case there seem to be two approaches:

1) the timeout that Tom suggested
2) a similar approach to loop-protect

For 1. you'd probably want a literal `setTimeout` that unmounts the preview frame if it has hung.  However, I'm not sure how you'd detect that it was in a recursive loop from the outside.  Any ideas?

For 2. we could transform the user's code before mounting it, so that components stop rendering automatically after a certain number have been rendered.

If you have a function like this:

```jsx
const MyComponent = function () {
    return(<MyComponent/>);
};
```

it could become

```jsx
let depth = 0;

const MyComponent = function () {
  depth++;
  return (depth > 5) ||
  (<> 
   {/* depth {depth} { }*/}
       <MyComponent />
  </>)
}
```

the commented out bit is just for illustration.
