### ISSUE TITLE
Certifications look buggy with new fonts

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#37378]
Please see below. The text has been shifted around a bit in some aspect ratios. We need to ensure that the text on certifications looks right on all screen sizes:

<img width="1149" alt="_5__freeCodeCamp_org_on_Twitter___We_are_taking_freeCodeCamp_down_so_we_can_deploy_some_major_changes__We_will_be_back_soon__In_the_meantime__our_YouTube_is_up_and_it_has_1_000__coding_tutorials_on_Python__SQL__Data_Science__and_Machine_Lea" src="https://user-images.githubusercontent.com/985197/67033512-8a482a00-f0db-11e9-9056-1f32dfa0a483.png">

**Comment by dboydgit** [comment]
Can I get steps to reproduce? I can't see this on my dev build with any screen size.

**Comment by moT01** [comment]
I can't reproduce this either. Although on one load of the above cert, I did get the date with a dark font color...
<img width="877" alt="Screen Shot 2019-10-18 at 7 20 31 AM" src="https://user-images.githubusercontent.com/20648924/67093673-d21c8f00-f177-11e9-8fd5-de29787b56cd.png">
But I couldn't reproduce this a second time.
Seems like maybe some of the intended css isn't getting applied intermittently or something.

**Comment by ahmadabdolsaheb** [comment]
@moT01, hmm.
it seems like a theme related issue.
all colors in the certificate should come from 
:root {} in the variables.css

**Comment by thecodingaviator** [comment]
Since we're dealing with formatting and whitespace of certificates here, should we not center this to the page?
![image](https://user-images.githubusercontent.com/34807532/67147731-05b10380-f2b5-11e9-8d9f-08b3d5335392.png)

**Comment by moT01** [comment]
Is it not already centered @thecodingaviator? I'm not sure what you are referring to.

So I think I figured out how to reproduce my issue. The date gets the dark font when you open a cert in a new tab or go to the URL through the address bar. But gets the correct font when you just open the cert in the current tab from the portfolio page. Can anyone else check this?

**Comment by thecodingaviator** [comment]
I’m referring to vertical centring. See the white gap between the end of the certificate and where the browser ends

**Comment by dboydgit** [comment]
I put in a pull request to center the certificates vertically on large screens. @moT01 I can't reproduce your font color issue. New tab and navigating with URL both show the correct font color for me.

@raisedadead I also can't reproduce the font offset in the first screenshot. So I don't think there is anything else that can be done on this issue unless someone can reproduce these.

**Comment by raisedadead** [comment]
> I also can't reproduce the font offset in the first screenshot. 

I am not very sure as well, could be some specific device or viewport size. Will check with the OP to test this.

Thanks for the PR.

**Comment by ojeytonwilliams** [comment]
The problems that @moT01 pointed out:

>  I did get the date with a dark font color...
> <img alt="Screen Shot 2019-10-18 at 7 20 31 AM" width="877" src="https://user-images.githubusercontent.com/20648924/67093673-d21c8f00-f177-11e9-8fd5-de29787b56cd.png">
> But I couldn't reproduce this a second time.
> Seems like maybe some of the intended css isn't getting applied intermittently or something.

were not addressed in https://github.com/freeCodeCamp/freeCodeCamp/pull/37427, so this should not have been closed.

**Comment by moT01** [comment]
Can anyone else reproduce that? or Quincy's issue? 

I can still reproduce mine on production, but not locally.

**Comment by raisedadead** [comment]
> I can still reproduce mine on production, but not locally. Perhaps it has worked itself out on master.

I will have a build pushed to dev within the hour. Would you like your user record there for testing?

**Comment by moT01** [comment]
Sure

**Comment by raisedadead** [comment]
Okay let's do a before and after, I am have added your user record to .dev, and will let you know again on this thread when I have pushed a build.

**Comment by ojeytonwilliams** [comment]
I can reproduce it on production. I haven't had chance to do locally, but my guess is you'll need to build the client to see it.

**Comment by raisedadead** [comment]
The changes have now landed in production as well. Can you check?

**Comment by ojeytonwilliams** [comment]
@raisedadead it's something to do with client-only routes.  If you build the client and then use `netlify dev` to serve it, you see the problem Tom found.   For some reason you get a 404 for the cert route and it loads, but the `body` gets `class="light-palette"` and so the certificate renders incorrectly. Everything works as expected when using `gatsby serve`.

**Comment by kmb40** [comment]
Hello - This may help debug the issue. 

I **do not** have this issue when viewing the certificate from my profile page - after clicking the "View Full Stack Certification" button. 
<img width="1377" alt="Screen Shot 2019-11-21 at 9 27 44 AM" src="https://user-images.githubusercontent.com/1646055/69346826-772bfb00-0c41-11ea-90e6-a3583401effc.png">

I do have this issue when viewing the certificate while visiting the url directly. 
<img width="1372" alt="Screen Shot 2019-11-21 at 9 31 17 AM" src="https://user-images.githubusercontent.com/1646055/69347193-0d602100-0c42-11ea-955e-982b0dc0d4e7.png">

**Comment by ahmadabdolsaheb** [comment]
i think some general theme based color styles are over writing that element styles, in this case if this case if we make the styles more specific, and apply to ```strong``` it should work.

![image](https://user-images.githubusercontent.com/4591597/69491083-58c43a80-0ea1-11ea-98c2-dc151d0e3fd8.png)

**Comment by thecodingaviator** [comment]
It's not just the fonts. The page sizing is also getting messed up when visiting from an external link. If you come from somewhere other than fCC, you'll see scrollbars.

**Comment by ahmadabdolsaheb** [comment]
> It's not just the fonts. The page sizing is also getting messed up when visiting from an external link. If you come from somewhere other than fCC, you'll see scrollbars.

I could not reproduce this on mac and chrome 78.0.3904.108. could you give tell me about the  browser and operating system you are using.

**Comment by thecodingaviator** [comment]
@ahmadabdolsaheb See scrollbar to the right when I open it externally
![image](https://user-images.githubusercontent.com/34807532/69970502-62563e00-1544-11ea-8d64-ac6c76a65569.png)

None if opened directly from fCC
![image](https://user-images.githubusercontent.com/34807532/69970549-700bc380-1544-11ea-8711-4dceb445d829.png)


Also, notice whitespace is different

**Comment by thecodingaviator** [comment]
Alright, since we've added the donation request, this issue has been rendered moot
