### ISSUE TITLE
We cannot reach the server to update your progress.

### ISSUE THREAD

**Issue by macengr** [freeCodeCamp/freeCodeCamp#37571]
**Edited by @moT01:**
## Anyone coming here with this issue should read through this, or specifically [go to this comment](https://github.com/freeCodeCamp/freeCodeCamp/issues/37571#issuecomment-547288864) and send an email.
<hr>

**Describe your problem and how to reproduce it:**

I've been trying to submit several projects for a week and I get the subject message.

**Add a Link to the page with the problem:**

All pages

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

Version 78.0.3904.70 (Official Build) (64-bit),
![Capture](https://user-images.githubusercontent.com/8150967/67624427-6cc34080-f7fe-11e9-9ab0-4740b7619d30.JPG)
 Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by nandumoura** [comment]
i have the same problem

**Comment by thecodingaviator** [comment]
I haven't been able to reproduce the issue. Can both of you please check again? If the issue is still there, try checking your browser's proxy config and network settings in general

**Comment by moT01** [comment]
Thanks for reporting this @macengr. It looks like this has been fixed and is waiting to be pushed to production. See https://github.com/freeCodeCamp/freeCodeCamp/issues/37381 for more info. We can close this since it has been resolved.

**Comment by macengr** [comment]
I'm not sure why you closed this because I am STILL unable to submit my projects. It's been over a week now. I've seen multiple people reporting this problem and it always ends the same way - oh, we fixed it, closed. It's not fixed until it works for the user.

**Comment by macengr** [comment]
Please see the comment I just left on 37571. It is most definitely NOT
resolved.

**Comment by moT01** [comment]
The reason this can be closed is because the issue has been fixed on our development environment. We don't need open issues for something that is fixed. I just verified that it is fixed locally. I'm not sure when the next time the code will be added to the live site will be; but once it is added, you will be able to submit your projects normally. Thanks.

**Comment by macengr** [comment]
No, still not working. My original data is the same (1st post). 3:09 PM EST 10/27/2019

**Comment by RandellDawson** [comment]
@macengr I am reopening this issue, due to you still having the problem.  Are you using any browser extensions which could be blocking the requests?

**Comment by macengr** [comment]
Not that I know of, at least, none that I wasn't using before this started.

**Comment by macengr** [comment]
I've made a recording for you:

https://www.loom.com/share/b6d7ad6899d7481a979ada644a1a93a6

**Comment by moT01** [comment]
Sorry for closing this prematurely @macengr. I can't reproduce this with any browser on High Sierra.

**Comment by broregard** [comment]
I've been getting the same error message. Doesn't matter what browser I use, although at this point I can no longer log into my account (signed up w/Github acct). I'm still logged into a session on Opera. Browser is up to date. No extensions. macOS 10.1.14

<img width="913" alt="Screen Shot 2019-10-27 at 6 41 09 PM" src="https://user-images.githubusercontent.com/11634920/67643084-8097a100-f8e9-11e9-805a-7c4acfe6e404.png">

**Comment by stevejh1** [comment]
I required a suggestion to solve [Yahoo 404 http](https://gmailtechnicalsupportnumbers.com/blog/fix-yahoo-mail-error-code-404/), I attempt all the steps known, and few more learned by internet if you have experience how to solve this please suggest the measures.

**Comment by broregard** [comment]
Now that my account has been merged #37457, the projects I submitted are showing up

**Comment by kelsiestevenson** [comment]
I am still experiencing the issue and I do not believe I have an account issue

**Comment by ojeytonwilliams** [comment]
Is anyone that is experiencing this issue able to log in and edit their user account settings?  The reason I ask is that that specific message should only appear if the browser can't detect the internet or the fcc servers have not returned your user details.

If not, then the problem is likely login issues, discussed further [here](https://github.com/freeCodeCamp/freeCodeCamp/issues/37457).

If yes and you can change your settings, submit other challenges and everything, aside from project submission, seems to be working, then this is definitely something new.

**Comment by kelsiestevenson** [comment]
Ok, I am unable to update my account settings. I receive this error when I try: 
![image](https://user-images.githubusercontent.com/23170565/67695962-5fcc5b80-f97c-11e9-804f-d0005d0c9a40.png)

I will follow the issue mentioned above

**Comment by macengr** [comment]
I redceive the same error as Kelsie when I try to change my settings (e.g., switch to dark mode or submit an about message):

https://www.loom.com/share/ccd4e968a1254a14a18ba53ed63d6027

**Comment by ahmadabdolsaheb** [comment]
Thank you for your patience.

We suspect this issue could be caused by of duplicate accounts.

If you could kindly send us an email support@freecodecamp.org with your username, we should be able to take a closer look and resolve this issue ASAP.

**Comment by nandumoura** [comment]
is not resolved

**Comment by kelsiestevenson** [comment]
After emailing support and having my duplicated accounts merged (for those following along, I had no idea that I had duplicated accounts - view issue #37457 for more info), I am able to submit my lessons and update my accounts settings. 

One buggy thing which I included in an email to support is that when I click the freeCodeCamp logo, it appears to log me out. I press Sign In and I am able to see my curriculum again though.

Thanks for the help with this issue.

**Comment by thecodingaviator** [comment]
@nandumoura 

> Thank you for your patience.
> 
> We suspect this issue could be caused by of duplicate accounts.
> 
> If you could kindly send us an email [support@freecodecamp.org](mailto:support@freecodecamp.org) with your username, we should be able to take a closer look and resolve this issue ASAP.

**Comment by ahmadabdolsaheb** [comment]
> After emailing support and having my duplicated accounts merged (for those following along, I had no idea that I had duplicated accounts - view issue #37457 for more info), I am able to submit my lessons and update my accounts settings.
> 
> One buggy thing which I included in an email to support is that when I click the freeCodeCamp logo, it appears to log me out. I press Sign In and I am able to see my curriculum again though.
> 
> Thanks for the help with this issue.

Our landing page looks like the log out version of /learn at the moment. It is likely that you have been redirected to the landing page without getting logged out.

**Comment by brianignacio5** [comment]
@ahmadabdolsaheb I sent an email to check if my account is duplicated.
