### ISSUE TITLE
404 Search "See all results for ..."

### ISSUE THREAD

**Issue by uwsd** [freeCodeCamp/freeCodeCamp#38039]
**Describe the bug**
Using the search-Field and clicking "See all results ..."

**To Reproduce**
1. Go to 'https://www.freecodecamp.org/'
2. Click on 'Search Field' and enter s.th. I did "Flutter" and then I clicked "See all results for Flutter"
3. See error: "404 Page not found"

I think the error is easy to fix: 
The automatic created result link after clicking has double "news"-part:  https://www.freecodecamp.org/news/news/search/?query=Flutter

if I manually remove one "news" as https://www.freecodecamp.org/news/search/?query=Flutter
the result would be the correct one.

**Comment by ojeytonwilliams** [comment]
@uwsd Thanks for the report!

It seems it's a problem with redirection.

- https://freecodecamp.org/ redirects to
- https://www.freecodecamp.org/news

and the link is to 

- https://freecodecamp.org/news/search/?query=flutter which redirects to
- https://www.freecodecamp.org/news/news/search/?query=flutter 

cc: @raisedadead

**Comment by scissorsneedfoodtoo** [comment]
Thank you for reporting this @uwsd. This was also a problem on /news. I deployed a quick fix and am working on PRs now.

I noticed that we could change the URLs in the search related files from https://freecodecamp.org/news/search/?query=flutter to https://www.freecodecamp.org/news/search/?query=flutter. This seems to get around the problematic redirect, at least for search results. Still an issue we need to investigate further for other use cases.

**Comment by raisedadead** [comment]
@scissorsneedfoodtoo search is still broken? I can't get anything to load for generic searches.

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, what sort of generic searches are not loading for you? Things seem to be working on my end whether I search from .org/ or .news/.

**Comment by ahmadabdolsaheb** [comment]
working on my side on news and learn from multiple locations.

**Comment by raisedadead** [comment]
![2020-01-15 18 41 11](https://user-images.githubusercontent.com/1884376/72437169-2a3f4d80-37c8-11ea-86f7-1be5cb56b4df.gif)

**Comment by ojeytonwilliams** [comment]
Should it say something like "No results for for 'this is a generic search', please try a different query"?

**Comment by scissorsneedfoodtoo** [comment]
Thanks for the gif, I see what you mean now.

The behavior should be a message that says "No tutorials found" and not to allow the search to complete. There's a PR for this on News [here](https://github.com/freeCodeCamp/news-theme/pull/88), and I'll start working on the implementation in the main repo.

**Comment by ahmadabdolsaheb** [comment]
I am going close this since the above prs address the issue. Feel free to reopen if you think this issue has been closed by mistake.

**Comment by raisedadead** [comment]
Has the fix landed on production. I am able to reproduce the issue?

**Comment by ahmadabdolsaheb** [comment]
@raisedadead has not landed yet on learn. but you could see the fix on /news

**Comment by raisedadead** [comment]
The query string is passed on to the news application. URL is available on the GIF that I sent.

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, we deployed the updated theme to News, so you shouldn't be able to enter a long string there and hit the search results page. Once the fix to Learn is deployed you won't be able to pass long strings with no hits to News like in the GIF.

**Comment by raisedadead** [comment]
Quick follow up, is there anything that is preventing us from deploying?

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, sorry for the delay in deploying. We just got access to the client VM to clear out the old builds. We'll do that later today and get all these changes out.

**Comment by raisedadead** [comment]
Great, thanks for confirming. Apologies I have added the keys to the VMs a couple days ago. I missed letting you know.

I have also cleared the older builds. You should be able to simply run a build.

Thanks.

**Comment by scissorsneedfoodtoo** [comment]
No worries man. Thank you for adding our keys. We should have checked to see if we had access yet. 

We're just about to go in now and run a build.

**Comment by scissorsneedfoodtoo** [comment]
This fix has been deployed. The problem in the gif above should no longer be possible on https://www.freecodecamp.org or https://www.freecodecamp.org/news.
