### ISSUE TITLE
Challenges (Front End Development Libraries Projects): Multiple tests breaks with React 18

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#45922]
Update: In an attempt to fix the issue with React 18 we have implemented delays to button clicks performed by the tests and before checking the DOM content. This isn't guaranteed to fix the issue for all projects.

If you want to make sure your project is not failing because of React 18 start by using the old render method.

```js
import ReactDOM from "react-dom";
import App from "./App";
ReactDOM.render(<App />,  document.getElementById("root"));
```

If that doesn't help try downgrading to React 17.

Using the [flushSync](https://react.dev/reference/react-dom/flushSync) function may also be an option, but that is really more of a last-resort type fix.

If your project still fails with React 17 it is likely not an issue with the tests.

---

Code that is passing using React 17 is failing with React 18.

It seems to be an issue with the new batch rendering and our tests. At this time, I'm not sure what the best solution is. I haven't really looked into it much.

### Affected Page

* JavaScript Calculator ✅ (the example project is passing but we may have to use a longer delay)

  * [PR](https://github.com/freeCodeCamp/testable-projects-fcc/pull/1454)

* 25 + 5 Clock ✅ (may still fail using React 18 and hooks)

  * [PR](https://github.com/freeCodeCamp/testable-projects-fcc/pull/1485)

* Drum Machine ✅ 

  * [PR](https://github.com/freeCodeCamp/testable-projects-fcc/pull/1452)

Tests: https://github.com/freeCodeCamp/testable-projects-fcc/blob/main/src/project-tests/

### Additional context

Forum threads:

https://forum.freecodecamp.org/t/drum-machine-test-7-is-failing/507800/
https://forum.freecodecamp.org/t/stuck-on-drum-machine-test-7/508120/
https://forum.freecodecamp.org/t/25-5-clock-pomodoro-timer-not-passing-test-12-decrease-break-time/504446/12
https://forum.freecodecamp.org/t/my-tests-don-t-make-sense-in-my-25-5-clock/504936

**Comment by Sboonny** [comment]
Related forum threads: 
https://forum.freecodecamp.org/t/25-5-clock-pomodoro-timer-not-passing-test-12-decrease-break-time/504446/12
https://forum.freecodecamp.org/t/my-tests-don-t-make-sense-in-my-25-5-clock/504936

**Comment by raisedadead** [comment]
@freeCodeCamp/dev-team 🤷🏽

**Comment by lasjorg** [comment]
I can fix the drum machine and calculator just by adding some simple delays between button click and DOM queries but I'm not sure what is going on with the 25 + 5 Clock. I'm not really sure how React is breaking the timer, it might be related to the MutationObserver but that is just a guess.

**Comment by lasjorg** [comment]
I pushed what I have just in case.

**Comment by ShaunSHamilton** [comment]
@lasjorg I started with the calculator, but am now mostly just playing with the Drum Machine

**Comment by ShaunSHamilton** [comment]
@lasjorg I cannot seem to fail the Drum Machine, but I have no idea what change worked... I converted the example to v18, by changing it into functional components, and it just works.

**Comment by lasjorg** [comment]
@ShaunSHamilton I made a PR for it. It was only the one display test that was failing and all it needed was again a small delay. I would assume the latest version of the CDN link has that fix.

If the PR for the calculator is acceptable then all that is left is the 25 + 5 clock.

**Comment by ShaunSHamilton** [comment]
🤦‍♂️ Right. My bad.

**Comment by lasjorg** [comment]
It's all good. If you figure something out for the 25 + 5 clock let me know. Still not sure how to fix that, or at least what I have tried so far didn't do much.

**Comment by fygen** [comment]
Hi my name is Fatih,
Is there something I can help you with? I am in 25+5 Clock project, I did the project fully functional for version 18.1. 
I used 17.0.0 version, no luck :) I need this certification because I got 2 certificates and I have to continue, I need a job and this certificate should have to be in my CV. Or I might start the same project with older version. Thank you for your help and I appreciate the efforts.

**Comment by Sboonny** [comment]
@fygen 
Faith, I will answer here instead of the forum, you can check its repo here: 

https://github.com/freeCodeCamp/testable-projects-fcc#testing-this-project

Here is the test itself:

https://github.com/freeCodeCamp/testable-projects-fcc/blob/main/src/project-tests/25-5-clock-tests.js

Although this issue isn't labeled help wanted, we are happy to hear your suggestions and what you will find

**Comment by fygen** [comment]
Thank you for your answer Muhammed I will be looking the information of
main page first and then check what I could do. Thanks

sincerely Fatih.

Muhammed Mustafa ***@***.***>, 19 Haz 2022 Paz, 23:05
tarihinde şunu yazdı:

**Comment by lasjorg** [comment]
@fygen If you need help with your project please open a thread on [the forum](https://forum.freecodecamp.org/).

If your project is not passing the tests using React 17 (or 18 using `ReactDOM.render`) then it is most likely an issue with your code and not the tests.

**Comment by fygen** [comment]
@lasjorg Here is the last state of my Clock [25+5 Clock](https://codepen.io/fygen/pen/WNMWvNX?editors=0011),

I opened a thread in FreeCodeCamp and @Sboonny guided me here. So many tests are failing and #time-left seems like not found, thats why I was looking for a solution. But the id with: time-left is there. Its a fully functional 25+5 Clock and I used useState & useReducer. Thank you for your interest. Much appreciated..

The problem with time-left
![image](https://user-images.githubusercontent.com/25952641/174501477-57bf190e-31e5-4444-b3be-280cb647c96f.png)

**Comment by lasjorg** [comment]
@fygen This issue is not the correct place to ask for help with your project. Use the forum thread instead.

If you check the example project you can see it passes all the tests, as does my own project. So it isn't an issue with the tests (with the correct version of React).

**Comment by RandellDawson** [comment]
Is there any plans to put a note or something for at least the 25+5 project regarding using React 17 vs. 18 when testing with the Test Suite?  This issue keeps popping up on the forum every day.  What is the status of fixing the tests to work with React 18?

**Comment by lasjorg** [comment]
I was thinking of adding a note, I'm just not sure where to put it.

I have still seen some campers fail tests with React 18 on the challenges that should have been fixed. They might work now with the example project but that doesn't mean they can't fail for some campers. Switching to React 17 seems to be the only solution for some projects I have seen.

So should the note be for all of the challenges and if so where do we put it?

> What is the status of fixing the tests to work with React 18?

I have gotten no closer to getting the 25 + 5 project tests to behave with React 18. As I said, I think it is the mutation observer used by the tests but I haven't looked at it again.

If anyone has an idea how to fix the tests for React 18 please let us know.

**Comment by anlach** [comment]
Hi @lasjorg - I'm going to take a look at the tests for the 25 + 5 clock. I've been going through the curriculum, and it took me a while to figure out it was my use of React 18 that was causing the tests to fail. The best way to avoid this issue for others in the future is to fix the tests, so I'm going to give it a shot. It might take me a while.

Please let me know if there have been any developments in the last couple weeks, or if there's anything else I should know.

**Comment by lasjorg** [comment]
@anlach Any help we can get is appreciated.

I don't really have anything new to report on the tests for the 25 + 5 project. I still think the mutation observer used has something to do with it and I'm not sure if it can be fixed or if it needs to be re-written without it. Also, that is just a guess, I have no real evidence for it.

**Comment by anlach** [comment]
Okay, @lasjorg, thanks. I gave it a try and messed with some delays.  They started passing for me locally. Here's the PR:
https://github.com/freeCodeCamp/testable-projects-fcc/pull/1466

**Comment by anlach** [comment]
Hey guys - nobody has responded to the PR, and I didn't name the branch properly, so I made a new PR: https://github.com/freeCodeCamp/testable-projects-fcc/pull/1485

**Comment by anlach** [comment]
Hi @ShaunSHamilton - any idea what the status is for accepting my PR?

**Comment by naomi-lgbt** [comment]
These should all be fixed now, I believe.

**Comment by lasjorg** [comment]
Well, the example projects pass now using React 18, but they are all old projects using class components.

Some projects are still failing when using functional components and hooks with React 18. I think the two projects that are the most problematic are the 25+5 clock and the calculator. My old 25+5 clock still fails with using React 18 with the latest PR code.

We may want to keep this issue open just to have some acknowledgment of the issue.

**Comment by mskDev0092** [comment]
This course needs upgrade now , Modern Hooks and Functional react should be introduced instead of Class based react and redux...

**Comment by lasjorg** [comment]
As the repository with the tests has been archived, we might as well close this issue.

**Comment by leopoldo-moreira** [comment]
the current version of react is 18.2.0.

Is this version still having problems for this challenge?

**Comment by lasjorg** [comment]
@leopoldo-moreira All versions using the new batch rendering are affected. I don't see that changing in future versions, but you never know.

**Comment by rossi-jeff** [comment]
has any progess been made on this front? I rewrote my pen using class components as one post said that was successful but still had no joy on markdown previewer

**Comment by lasjorg** [comment]
@rossi-jeff The test library was archived, it is no longer being developed.

If your app does not pass the tests using the old render method or with React 17 the issue is most likely with your code and not the tests. Ask for help on the forum and not in this issue.
