### ISSUE TITLE
Unable to link GitHub account

### ISSUE THREAD

**Issue by yaynick** [FreeCodeCamp/FreeCodeCamp#6429]
I'm unable to link my GitHub account to FreeCodeCamp (http://www.freecodecamp.com/fccbd1cb0b2). It gives me the message: Your GitHub is already associated with another account. You may have accidentally created a duplicate account. No worries, though. We can fix this real quick. Please email us with your GitHub username: team@freecodecamp.com.

I sent an email to team@freecodecamp.com last week and have not yet heard back.

**Comment by BerkeleyTrue** [comment]
You've already created an account with your Github account. I can delete the Github one, then you'll be able to link it to that account listed above or you can sign out and then signing with your Github account.

**Comment by yaynick** [comment]
Yes if you could go ahead and delete the Github one so then I can relink it that would be cool. Many thanks.

**Comment by BerkeleyTrue** [comment]
Done. Happy Coding!

**Comment by yaynick** [comment]
@BerkeleyTrue Hate to bring this back up, but still having issues...

<img width="1142" alt="screen shot 2016-01-25 at 1 10 26 am" src="https://cloud.githubusercontent.com/assets/9129683/12546710/7b3e00e6-c300-11e5-9b0f-d0125e96ab3d.png">

**Comment by BerkeleyTrue** [comment]
How about now?

**Comment by yaynick** [comment]
It works! Many thanks.

**Comment by Earlq** [comment]
@BerkeleyTrue can you please do the same for me???

**Comment by TausifAlam121** [comment]
Sir I am in the same trouble.Could you help me too?

**Comment by Earlq** [comment]
Haha hey man I started fresh by logging in with the GitHub account

**Comment by dzehavi** [comment]
I had the same issue.

1. I first signed in to freecodecamp using my GitHub account, 
2. I signed out of freecodecamp, 
3. I signed in to freecodecamp using my LinkedIn account.
4. I couldn't link my GitHub account to the freecodecamp account that was created using my LinkedIn account. 

The reason was that my GitHub account was already linked to the freecodecamp account which was created using my GitHub account. 

To resolve, I signed in to freecodecamp using my GitHub account, deleted this freecodecamp account, then signed in to freecodecamp using my LinkedIn account and now I was able to link my GitHub account to it.

Hope this deletion isn't too painful... fortunately for me I made all the progress on the LinkedIn account.

**Comment by LordQuanza** [comment]
i got the same issue can somebody help me?

**Comment by saloni29993** [comment]
Can someone help me too!

**Comment by aweintraut** [comment]
So - is there a procedure for just saying "please delete the old freecodecamp account association with github"?

I found this site few months ago and played around with a login, which it associated with my github, then forgot about it.  I created a new account recently, went through a section, and then realized when I hit the link to Github that the old account was out there.

I want to keep my Github. I want to keep my NEW freecodecamp account. I thought perhaps unauthorizing it in Github would do it but looks like FreeCodeCamp is saving a ref to my Github on their server under the old account?

**Comment by aweintraut** [comment]
Answered my own question:
1.  Log in to FreeCodeCamp via Github. This will be on the account you do NOT want, probably one without progress through lessons.  
2.  Delete the account (again double-checking it doesn't have progress you want to retain)
3. Now log in to FreeCodeCamp via email on the account you want to associate wth GitHub.
4. Click the link to Github (which now should work).
G'luck all!

**Comment by dcdunham** [comment]
I've seen the instructions from FreeCodeCamp about logging in with our GitHub accounts.  I've been trying this for some time, but I always get a message that says "Oops!  Something went wrong.  Please try again later."  I've tried it while logged into GitHub, and I've tried it while logged out.  Same thing happens.
![image](https://user-images.githubusercontent.com/28540801/30037253-1a7b4640-9187-11e7-9bef-76a7b0c7bdb7.png)
