### ISSUE TITLE
Progress not being saved on video challenges

### ISSUE THREAD

**Issue by MDAWebDev** [FreeCodeCamp/FreeCodeCamp#6912]
I answer all of the quiz questions correctly and the box pops up saying "Congratulations!
Hike completed. Saving..." but then when I go back to the map or my account page there is no record of me having completed the challenge. No green checkbox, no mark on the calendar, and no point. 

I did the first video challenge yesterday and everything worked like it's supposed to, but upon logging back in today no progress is being after I complete each subsequent challenge.

**Comment by QuincyLarson** [comment]
@MDAWebDev Thanks for reporting this. @BerkeleyTrue could you take a quick look at the logic?

**Comment by Greenheart** [comment]
I've just experienced this problem myself.

I used my laptop (Firefox 44, Ubuntu Linux) with an unreliable mobile network to complete both **JavaScript Lingo** and **Chrome Developer Tools** but none of my progress was saved.

However, when I used WiFi to complete **Computer Basics** and **The DOM** four days ago everything worked fine.

**Comment by Takumar** [comment]
I can just say that it did not work yesterday also for me. I watched two whole videos, answered questions, and I don't have these two videos on the map checked.
- Computer Basics: Content Delivery Networks
- Analog vs Digital and File Compression

**Comment by GFore** [comment]
I'm having the same issue. I watched the first 5 Computer Basics videos over Feb 10-11 and my progress was recorded for those. I watched the next three videos in the series and completed the quizzes today (Feb 12) but progress is no longer being recorded. My Brownie points increment in upper right corner immediately after completing a quiz, but if I go to the map or to my profile, the progress on those videos (and my Brownie points) get reset to where it was before the videos. I've completed other tasks today that did get recorded, so the problem appears to be only with the Video Challenges. I'm accessing the course on my desktop PC and got the same results with both Chrome and Firefox.

**Comment by trueskawka** [comment]
Same here. Tried it twice just now, the progress has not been saved.

**Comment by CEREBR4L** [comment]
I am also having the same issue... Having completed all comp basics, the dom and js lingo upon going to my profile I can see the progress has now been saved at all.

**Comment by ltegman** [comment]
This is what happens in the console when you submit a video challenge:
![videos___free_code_camp](https://cloud.githubusercontent.com/assets/1381313/13031003/a03eb8ec-d271-11e5-9627-47651fa18d3b.png)

**Comment by trueskawka** [comment]
Still not working for me.

**Comment by CEREBR4L** [comment]
@trueskawka Same!

**Comment by Greenheart** [comment]
@trueskawka @CEREBR4L The fix is probably not yet pushed to the production servers. It usually takes up to a day or so before fixes get applied :)

**Comment by bugron** [comment]
@Greenheart is correct. This fix is in staging branch and it will be push to production soon.

**Comment by trueskawka** [comment]
@Greenheart @bugron Thanks for clarifying that :)

**Comment by bugron** [comment]
@trueskawka it's now pushed to production so this issue should be fixed now.

**Comment by MDAWebDev** [comment]
I'm still having this problem unfortunately. My progress was saved on the first video challenge I completed today after logging in but my completion of the subsequent challengers was not recorded. Just like what @GFore said, the brownie points counter in the upper right-hand corner increments as if the progress is being saved  but if I open the map or my profile I can see that they aren't being recorded.

**Comment by BerkeleyTrue** [comment]
Video lessons where removed from profile view.

**Comment by MDAWebDev** [comment]
Yes, but the brownie points gained from completing the video challenges should still appear on the profile view.

**Comment by BerkeleyTrue** [comment]
Brownie points earned from completing them are still recorded. There is nothing on the profile view to distinguish one brownie point from the other.

**Comment by MDAWebDev** [comment]
They're not being recorded and green check marks aren't being added to the video challenges I've completed. I should have 421 brownie points right now but I only have 414 because the only the first video challenge I completed was recorded.

**Comment by GaryLomberg** [comment]
Still no check marks being added to completed challenges in the computer basics section.
Brownie points are also still not being added for completing the challenges
