### ISSUE TITLE
Waypoint: Add Borders Around your Elements

### ISSUE THREAD

**Issue by subam** [FreeCodeCamp/freecodecamp#743]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-borders-around-your-elements has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

https://files.slack.com/files-pri/T04B7Q2PP-F053G1WCJ/untitled.jpg

Even though i have made the border with 10px, style solid of class .thick-green-border, a green tick does not appear in the objective making me unable to mark the challange as complete.

**Comment by ajboilanger** [comment]
Just tried it, and while I'm not sure why this works when I swapped the order of the elements within the class, it worked... see photo:

![image](https://cloud.githubusercontent.com/assets/9096129/7893737/a0b65c36-062e-11e5-9f76-c4dac468e994.png)

**Comment by QuincyLarson** [comment]
I've now fixed this.

**Comment by europaradise** [comment]
I still can't solve this. I tried switching them around too and I only have 2 correct.

**Comment by suezl** [comment]
Neither can I. This is how I've done it, could it be another way?

<img class="smaller-image" src="https://bit.ly/fcc-relaxing-cat">
<img class="thick-green-border">

<style>
  
  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
  }
  
</style>

**Comment by iyania** [comment]
still couldn't do it.

**Comment by sasory21** [comment]
everything is written fine in the photo , thank you !

**Comment by juniorcito32** [comment]
h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed eve

**Comment by texas2010** [comment]
@juniorcito32 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by Reekaser** [comment]
Euro paradise...make sure your img class is like this:
<img class= "smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

**Comment by thisisSuresh** [comment]
Finally I did it!than you@ajboilanger

**Comment by TheIndiglo** [comment]
Helped me with my issue, many thanks!
