### ISSUE TITLE
Wrong link href for jQuery JSON function

### ISSUE THREAD

**Issue by nickbarry** [FreeCodeCamp/freecodecamp#919]
Challenge http://www.freecodecamp.com/challenges/zipline-use-the-twitch.tv-json-api has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Step #13: "Remember to use RSAP if you get stuck. Try using jQuery's $.getJSON() to consume APIs."
...links incorrectly to this url: http://api.jquery.com/jquery.each/

It should link to: http://api.jquery.com/jquery.getjson/

Unless that misdirection is meant to be tricky for the student ;)

**Comment by LumenTeun** [comment]
This is a duplicate of #918

**Comment by arukomp** [comment]
Kind of. This one is referring to a different page (challenge/zipline), but I did notice that all of the Ziplines have the same bug.

**Comment by ahstro** [comment]
This was fixed ages ago, right? Please close.

**Comment by nickbarry** [comment]
This isn't actually fixed. The erroneous link still exists in these ziplines:
* http://www.freecodecamp.com/challenges/zipline-build-a-random-quote-machine
* http://www.freecodecamp.com/challenges/zipline-show-the-local-weather
* http://www.freecodecamp.com/challenges/zipline-use-the-twitch.tv-json-api
* http://www.freecodecamp.com/challenges/zipline-stylize-stories-on-camper-news
* http://www.freecodecamp.com/challenges/zipline-wikipedia-viewer

Maybe it's not an issue because we'll be switching over to the content at beta.freecodecamp.com soon? But I thought you should know that the issue hasn't actually been fixed yet. Actually, the only reason that it isn't an issue on the beta site is that none of the ziplines seem to link directly to the jquery json page.

**Comment by ahstro** [comment]
@nickbarry This was fixed in `staging` prior to the branch being available through beta.freecodecamp.com. Now they seem to have changed how the ziplines look, so it wouldn't be an issue regardless.
Since all changes seem to happen on the `staging` branch before ending up in production, issues that are fixed in `staging` should probably be considered fixed, even though it might be better to merge small fixes like this into production at a quicker rate than what is the current reality.

**Comment by nickbarry** [comment]
@ahstro Thanks for the explanation! That makes sense. I'm not privy to staging, so I didn't realize it had been fixed there.
