### ISSUE TITLE
Camper getting "Authorisation Required" error when toggling night mode

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#9196]

**Comment by Oluwasetemi** [comment]
I think it is due to 2 factor authorisation enabled.

**Comment by raisedadead** [comment]
This is an duplicate of #8923, the analysis so far us (/cc @BerkeleyTrue) is that we need to replace the jQuery AJAX request by plain XHR 

This is also going to affect some of the campers and not everyone, a workaround for now is to use FireFox. The issue seems to happen only on Chrome.

**Comment by SzeregowiecPL** [comment]
![9ae6a25c9a7b4ae9b7429e227f07c3ea](https://cloud.githubusercontent.com/assets/18371979/16744370/14fdb246-47b1-11e6-9aef-9a5fd4046a08.png)

**Comment by ricardo-raog** [comment]
Hi. I'm on Firefox 47 and I have the same error.

**Comment by raisedadead** [comment]
@ricardo-raog thanks a lot for reporting.

**Comment by raisedadead** [comment]
Update: This will be resolved once we have the Free Code Camp website on react, very soon.

**Comment by QuincyLarson** [comment]
This is fixed on React. Closing.

**Comment by JustinRyanBlankenship** [comment]
This is still happening for me on firefox...I am a camper.

**Comment by JustinRyanBlankenship** [comment]
This has been fixed on Chrome but is broke on firefox... I am using a Macbook.

**Comment by raisedadead** [comment]
@JustinRyanBlankenship I can't seemingly reproduce this. Do you mind sharing the version details of your OS and the browser?

**Comment by GordonBombay88** [comment]
Still a problem on Chrome but works on Firefox

**Comment by cmorlee** [comment]
having this problem on chrome... help

**Comment by raisedadead** [comment]
@GordonBombay88 @cmorlee 

We are aware of this issue and it has been fixed, but unfortunately this has not reached the main website.

We will ship the fix, along with the new react version of Free Code Camp in the upcoming release. This might take a while, until then please bear with us.

**Comment by cmorlee** [comment]
This doesn't make sence seeing that my co-worker is using the camp and has
night mode activated on chrome.

**Comment by raisedadead** [comment]
> please use an alternate browser like Firefox as a workaround.

**Comment by bfarley88** [comment]
I can't wait until I get good enough at coding to know why this is happening and what I can do to fix it, myself. :) I'm on chrome and I can't update my email or switch to night mode. I get the message, "Authentication Required"

**Comment by raisedadead** [comment]
@bfarley88 Hey Brandon, this is fixed, but we are in the middle of pushing the fixes to the main website.

Meanwhile please check my comment above:
> please use an alternate browser like Firefox as a workaround.

**Comment by bfarley88** [comment]
@raisedadead Thank you for the quick response. I will wait until the fixes have been pushed. Firefox doesn't run too well on my macbook. If I get desperate for darkness, I'll just use the chrome app, Dark Reader, and deal with the aliased font, lol. Take care.

**Comment by szazadikablak** [comment]
I know the reports were sent months ago,but i am still unable to use Night Mode on Chrome. :/

**Comment by SUBstylee** [comment]
@szazadikablak Was having the same problem, but signing out then back in fixed it.  Hope that works for you.

**Comment by szazadikablak** [comment]
@SUBstylee wow,its working! Thanks for the tip !

**Comment by HeaTx** [comment]
@SUBstylee thanks for the tip! I was having the same issue (first time in freeCodeCamp)

**Comment by JamesMarie** [comment]
@SUBstylee that totally worked! Signed out and right back in... no authorization required here! Night mode is on!  Thanks!
